### ISSUE TITLE
createAutoField: Cannot use 'in' operator to search for 'options' 

### ISSUE THREAD

**Issue by kestarumper** [vazco/uniforms#1019]
## Problem description
When providing a schema like
```ts
const schema = {
  type: 'object',
  properties: {
    username: {
      uniforms: {
        component: 'TEXTFIELD', // <-- This causes error
      }
    }
  },
  required: ['username'],
};
```
the `createAutoField` throws errors (or rather `AutoField` created from it) when checking for `options` property with the following error:
```
TypeError
Cannot use 'in' operator to search for 'options' in TEXTFIELD
```

## Background
I've tried migrating from a custom AutoField to the one created by `createAutoField` but we were using a _component map pattern_ and we were using the `uniforms.component` schema property for the mapping.
```ts
// example, not an actual code
type componentMap = {
    [key: string]: React.ComponentType<T>;
}
``` 
So when `useField` is executed inside the `AutoField` created by `createAutoField` it uses this `component: "TEXTFIELD"` and then we get an error during check for `'options' in component` because `component` is a `string` and and not an `object`.

## Details
- Affected package: `"uniforms": "3.5.1"`
- Reproduction: [Sandbox](https://codesandbox.io/s/sleepy-shirley-o4mix)

**Comment by radekmie** [comment]
@kestarumper While I was working on a test for the PR, I realized that adding a check for `component` being an object will not work anyway. The point is, that we do call `createElement` on `component.Component` or `component` anyway, therefore `TEXTFIELD` won't work.

@wadamek65, @Monteth: Do you have any comments here? Because I think that we won't be able to make it work without significantly changing the `createAutoField` function.

**Comment by kestarumper** [comment]
@radekmie for me the problem was that
```ts
const component = props.component ?? componentDetector(props, uniforms);
```
first takes `props.component`, but in my case, I would like to use this keyword to determine the `component` based on the `componentDetector`. If we could detect if `props.component` is not a `React.ComponentType<unknown>` then we could do something with this (to be discussed I guess).

I see this is just a collision of _reserved_ fields. To be honest, a fix on my side would be to just rename this `component` to `componentName` in the schema, however it would require me to change a lot of places in our project because we used it before uniforms 3.

One of the solutions is to just block this keyword `component` and treat it as "reserved". We might just throw more verbose errors that `props.component` needs to be a proper React component. I'm not sure that we could use a `Symbol` there.

The other solution is to fallback first to `componentDetector` if `props.component` is not a React component, and eventually display the error that resolved component needs to be a React component.

**Comment by radekmie** [comment]
> The other solution is to fallback first to componentDetector if props.component is not a React component, and eventually display the error that resolved component needs to be a React component.

The problem is that a string _is_ a valid component. But not every string. And it also differs between environments, as one can have a custom renderer or use WebComponents.

Unfortunately, I think we'd have to pass on this one. Changing it e.g., in a way that `componentDetector` is _always_ called would be a breaking change. But let's give it some time, maybe someone else will have another idea.

**Comment by radekmie** [comment]
It turns out, there's no way to implement it without introducing a breaking change. The solution is to use a different name instead of `component` - this one remains "reserved" for the `AutoField`.
