### ISSUE TITLE
Update from 3.5.5 to 3.6.0 breaks API

### ISSUE THREAD

**Issue by bennycode** [vazco/uniforms#1031]
I just upgraded uniforms & uniforms-material from v3.5.5 to v3.6.0 in my TypeScript project and it looks like it introduced breaking changes. 

It wants me to change my `onSubmit` handler from:

```ts
    <AutoForm
      schema={userAddBridge}
      onSubmit={async (model: UserEntityProps) => {
        // ...
      }}
    />
 ```

to:

```ts
    <AutoForm
      schema={userAddBridge}
      onSubmit={async (DeepPartial<UserEntityProps>) => {
        // ...
      }}
    />
```

Is this intentional and are there any more breaking changes?

Best,
Benny

**Comment by wadamek65** [comment]
Hi @bennycode ,

Yes, this is intentional. In v3.6.0 we have added proper typings to all form components which may result in these errors. Please refer to the [documentation here](https://uniforms.tools/docs/faq#why-am-i-suddenly-getting-type-errors-in-my-form-components) for a workaround if you are unable to add the correct type.

If you notice any inconsistencies in the new types, please let us know and we'll try to address them.

**Comment by radekmie** [comment]
As @wadamek65 said, it was an intentional change - previously there were basically no types at all. If there are other issues, do let us know!
