### ISSUE TITLE
[V3.8] - Package uniforms-bridge-json-schema regex problem on safari

### ISSUE THREAD

**Issue by yudao** [vazco/uniforms#1088]
Affected Package: ```uniforms-bridge-json-schema```
Affected version: ```3.8```
Error after run npm run dev: ```SyntaxError: Invalid regular expression: invalid group specifier name```
Affected OS: ```Safari```

Regex problem uniquely on Safari (This is because Safari browser does not support regular expression zero assertion in two// formats:<= , ?<!).

Chrome is OK.

I have tested all my packages and only the upgrade from uniforms-bridge-json-schema from 3.6.2 to 3.8 create this error.

**Comment by JanMP** [comment]
Same problem here. Works with 3.7.0 but breaks on 3.8.

**Comment by wadamek65** [comment]
Hi,

Thanks for reporting the problem. The issue was most likely introduced in: https://github.com/vazco/uniforms/commit/331f717fca768b0f82315023522b6b8054284ebb and is probably related to [this RegEx](https://github.com/vazco/uniforms/commit/331f717fca768b0f82315023522b6b8054284ebb#diff-194906e60835baf3cb7b0bd5e698f97e9115694e5fe00dd34d1753ae3a62dd5cR37).
