### ISSUE TITLE
Forwarding of `disabled` prop with `useField`

### ISSUE THREAD

**Issue by radekmie** [vazco/uniforms#1094]
### Discussed in https://github.com/vazco/uniforms/discussions/1093

<div type='discussions-op-text'>

<sup>Originally posted by **simplecommerce** February 24, 2022</sup>
Hi,<br>
I have a Checkbox field that I built using `useField(props.name, props, { absoluteName: true });`.
When I set `disabled` on the `AutoForm` component, it passes the `disabled` state correctly to my Checkbox.<br>
In my current scenario, I need to disable the Checkbox but not the whole form, so I am passing `disabled={disabled}` to my component and it seems to disable it properly when true.<br>
The issue I am having is when the `disabled` prop I am passing is `undefined`, it doesn't seem to recognize the `AutoForm` `disabled` prop no more, it only sees `undefined`.<br>
Is this normal behavior?
Sorry if I am not being clear.
</div>

<br>

This is a bug - the [order of merged props in `useField`](https://github.com/vazco/uniforms/blob/29d1505db233e7061f0d729abb425cb129f125d4/packages/uniforms/src/useField.tsx#L108-L125) is partially incorrect, as `state`-related props should get inferred from the props, but not get overridden by them. However, it's unclear whether moving `state` lower will help:

```diff
   const fieldProps: GuaranteedProps<Value> & Props = {
     id,
-    ...state,
     changed,
     error,
     errorMessage,
     field,
     fieldType,
     fields,
     onChange,
     value,
     ...schemaProps,
     ...props,
+    ...state,
     label,
     name,
     // TODO: Should we assert `typeof placeholder === 'string'`?
     placeholder: placeholder as string,
   };
```

As this will override any `schemaProps`. Maybe we should change the [`state`](https://github.com/vazco/uniforms/blob/29d1505db233e7061f0d729abb425cb129f125d4/packages/uniforms/src/useField.tsx#L49-L52) as well? My suggestion:

```diff
   const state = mapValues(context.state, (prev, key) => {
-    const next = props[key];
+    const next = props[key] ?? schemaProps[key];
     return next !== null && next !== undefined ? !!next : prev;
   });
```

It'll fix this bug without backward-incompatible changes (except for getting rid of any `undefined` or `null`s), but will drift away from the [`connectField` logic](https://github.com/vazco/uniforms/blob/29d1505db233e7061f0d729abb425cb129f125d4/packages/uniforms/src/connectField.tsx#L61-L64).

What do you think @simplecommerce, @Monteth, @wadamek65?

**Comment by simplecommerce** [comment]
@radekmie 

I don't know if its a bug though.

In my "custom" field, I am doing this:

`<CustomFIeld disabled={get(props,"disabled")} />`

If `disabled` is `true` it would disable it, but if the prop doesn't exist, it would be `undefined`.

I think in your logic, you would have to clean the `undefined` attributes so that they don't overwrite the default ones.
But should this be part of your logic, or should it be the responsibility of the users using of your library?

Right now in my project I am doing this to solve it:

`...(!isUndefined(disabled) ? { disabled } : {})`

In your example, if you switch the `state` to be after `props`, it wouldn't work I think, because if I set `disabled` to `true` in my props, the state would overwrite it?

Just thinking outloud.

**Comment by radekmie** [comment]
> But should this be part of your logic, or should it be the responsibility of the users using of your library?

I partially think it is a bug - we recommend the users to specify this prop and it's marked as optional (e.g., `disabled?: boolean`). However, we may want to enable [`--exactOptionalPropertyTypes`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#exact-optional-property-types---exactoptionalpropertytypes) and call it a day (i.e., it's _optional_, not _optional or `undefined`_).

I do agree that the workaround with conditionally passing this prop is fine, but I'm not sure whether it should be required.

**Comment by wadamek65** [comment]
@radekmie I don't quite understand how `[--exactOptionalPropertyTypes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#exact-optional-property-types---exactoptionalpropertytypes)` would help in this case as it would not enforce this on the consumer of the API and people could still pass explicit `undefined` as a prop? Or would it help in some other way?

Also, perhaps [`lodash/mergeWith](https://lodash.com/docs/4.17.15#mergeWith) could be an option too since it would allow us for replacing the `undefined`s rather easily while keeping the spread order we would like to have.

**Comment by radekmie** [comment]
@wadamek65 It's not going to _fix_ it, but with that enabled we'll be safe from falling into this problem ourselves. About this task, we'd have to say in the docs explicitly, that it's _optional_, not "`undefined`-able".

**Comment by simplecommerce** [comment]
I think merge or mergeWith would work. I tested the following and it doesn't replace the disabled option when undefined.

```
var state = {
    disabled: false,
};

var schema = {
    disabled: undefined
}
 
var props = {
    disabled: undefined
};
 
_.merge(state,schema,props);
```

Your order could be kept without changing it.
Also if there are any other states that can be overwritten by the schemaProps or props, this would help too in those cases.

You would have to check if going this routes could impact or break anything in your overall logic and different scenarios.

**Comment by radekmie** [comment]
Right, we'd have to test it... I will let you know about that.

Sorry for it taking so long though.

**Comment by simplecommerce** [comment]
> Right, we'd have to test it... I will let you know about that.
> 
> Sorry for it taking so long though.

No worries, I didn't think it was a bug in the first place and only stumbled upon it because of a specific scenario.

Not related to the current issue, but have you guys ever thought about having a method similar to `modelTransform` that would allow the user to change the `schemaProps` on the fly, like in this case, to disable a field without having to create a custom component?

Example, in this scenario, when I toggle the `fieldBoolean` it would set `disabled` to true to the field that I want disabled.
It could maybe even work async, in case a user would want to pull some data to validate and then update the schema.

```
const model = {
   fieldBoolean: false,
   customField: ""
}

const schemaTransform = (model,schema) => {
   const newSchema = { ...schema };

   if (model.fieldBoolean === true) newSchema.customField.disabled = true;

   return newSchema;
}

<AutoForm model={model} schemaTransform={schemaTransform} />
```

I don't know if its doable or even worth the trouble in your different use cases, but just thought I'd share the thought.

**Comment by radekmie** [comment]
> Not related to the current issue, but have you guys ever thought about having a method similar to `modelTransform` that would allow the user to change the `schemaProps` on the fly, like in this case, to disable a field without having to create a custom component?

We actually use custom `AutoField` for that, as it can access the props, context, and any hooks you need. Give it a try and let us know.

**Comment by simplecommerce** [comment]
> > Not related to the current issue, but have you guys ever thought about having a method similar to `modelTransform` that would allow the user to change the `schemaProps` on the fly, like in this case, to disable a field without having to create a custom component?
> 
> We actually use custom `AutoField` for that, as it can access the props, context, and any hooks you need. Give it a try and let us know.

I think it wouldn't work in my case, in my usage, I created custom components using `useField` inside all of them and I place them in a custom layout without relying on AutoField and underlying themes.

So in order to pass disabled to a component based on context and model, I created a `DisableIf` component that I wrap around my custom component (if needed).

**Comment by radekmie** [comment]
Sure, a `DisabledIf` is also totally fine. If you have something particular in mind, let's create a separate discussion for that.

**Comment by radekmie** [comment]
I've run some tests:
* We can't use `_.merge`/`_.mergeWith`, as it's deep copying the objects and it causes problems with props like `children`. (It's also a performance hit.)
* A handmade version of `_.merge` that does the exact same thing but shallowly works for most cases, but breaks a few tests, as passing `value={undefined}` in props no longer works ([test](https://github.com/vazco/uniforms/blob/4bf978dc51c95371669ae24f7d15737c88c7862c/packages/uniforms-unstyled/__tests__/NumField.tsx#L118-L158)).
    * This test is not _that_ important but highlight an important point: passing `undefined` in props can be used as a way to disable certain schema props. It's important for custom fields that may rely on external libraries, etc.

I have to put more thought into it.

**Comment by simplecommerce** [comment]
> I've run some tests:
> 
> * We can't use `_.merge`/`_.mergeWith`, as it's deep copying the objects and it causes problems with props like `children`. (It's also a performance hit.)
> * A handmade version of `_.merge` that does the exact same thing but shallowly works for most cases, but breaks a few tests, as passing `value={undefined}` in props no longer works ([test](https://github.com/vazco/uniforms/blob/4bf978dc51c95371669ae24f7d15737c88c7862c/packages/uniforms-unstyled/__tests__/NumField.tsx#L118-L158)).
>   
>   * This test is not _that_ important but highlight an important point: passing `undefined` in props can be used as a way to disable certain schema props. It's important for custom fields that may rely on external libraries, etc.
> 
> I have to put more thought into it.

maybe you can only merge the props that are part of state and exclude children and also useMemo to compare for any changes so it doesn't always call the merge?

**Comment by radekmie** [comment]
Special handling of these props would make the implementation even harder. I think that the only reasonable solution **for now** is to leave the code as it is and add a point about that in the docs (+ maybe in JSDoc?). We can get back to it in v4.
