### ISSUE TITLE
Explicit typings for keys allowed in schema for JSONSchemaBridge

### ISSUE THREAD

**Issue by bennycode** [vazco/uniforms#1097]
I am using the `JSONSchemaBridge` and it allows to pass in a `schema` of type `Record<string, any>` which allows any key name. Is it possible to provide a stricter typing here so developers get to know that there are specific properties such as `title`, `type`, `properties` and `required` (as listed here: https://uniforms.tools/docs/api-bridges/#jsonschemabridge)?

**Comment by radekmie** [comment]
Hi there @bennycode! I fully understand where is this coming from, but there's the thing: a schema itself can look completely different. For example, it may use a `$ref` and `definitions` pair to define the schema instead of `properties` directly. Ideally, we would use something like [`JSONSchemaType<T>`](https://github.com/ajv-validator/ajv/blob/95b15b683dfb60f63c5129b0426629b968d53af8/lib/types/json-schema.ts#L143-L146) or [`SchemaObject`](https://github.com/ajv-validator/ajv/blob/95b15b683dfb60f63c5129b0426629b968d53af8/lib/types/index.ts#L15-L21) from `ajv`, but on the other hand, the bridge itself does not depend on this library.

You can create your own wrapper for `JSONSchemaBridge` using these types - I did that too. I'm not sure how we should proceed with it in the package though.

**Comment by bennycode** [comment]
Thanks for your fast response. Your explanation makes sense to me. Can you point me to demo code where you have applied [JSONSchemaType<T>](https://github.com/ajv-validator/ajv/blob/95b15b683dfb60f63c5129b0426629b968d53af8/lib/types/json-schema.ts#L143-L146)?

**Comment by radekmie** [comment]
It's in a project I cannot share, but the idea is very simple:
```ts
function createJSONSchemaBridge(schema: JSONSchemaType<any>) {
  const compiledSchema = ajv.compile(schema);
  function validator(model: object) {
    compiledSchema(model);
    return compiledSchema.errors?.length ? { details: compiledSchema.errors } : null;
  }

  return new JSONSchemaBridge(schema, validator);
}
```

**Comment by bennycode** [comment]
Thank you! I will give it a try. 😀
