### ISSUE TITLE
SubmitField with value

### ISSUE THREAD

**Issue by mariusrak** [vazco/uniforms#1157]
With classic html forms, you can have multiple submit buttons and then differentiate action based on which button was clicked to submit the form. I think this is not possible with uniforms. Could we somehow get value of a `SubmitField` clicked?

**Comment by radekmie** [comment]
Hi @mariusrak. We don't expose such API and don't plan to, but you could do one of these two things:
1. Implement custom buttons that'd call `formRef.submit()` directly. Because you assign them to the buttons, you already know which one is which.
2. Use the `event` argument of `onSubmit` event handler on `BaseForm` by extending it. It won't guarantee its presence, though, as it may be called programmatically.
