### ISSUE TITLE
Compatibility with StrictMode

### ISSUE THREAD

**Issue by Akshaya-009** [vazco/uniforms#1194]
After updating uniforms and uniforms-unstyled to version `3.10.1`,  unable to see the values in the input field.

Please check the issue and update us on the same.

Attaching Codesandbox link for the reference: 

[Click to open codesanbox](https://codesandbox.io/s/uniform-tools-cbppr4?file=/src/App.js)

**Comment by wadamek65** [comment]
Hi @Akshaya-009 , thank you for the issue report.

The issue you are seeing is not caused by `uniforms@3.10.1` update directly, but rather by the version of `react` being 18. The issue seems to go away if you remove `StrictMode` from the application, so there may be some idempotency problem within core `uniforms` logic. We will investigate this further and try to resolve it, but depending on the outcome, the fix may be too complex and may have to be postponed to `uniforms@4`. We will keep you updated on this issue.

**Comment by sprasad02** [comment]
@wadamek65 Removing `StrictMode` works. Until the fix is released can this be added to the doc so that it might be helpful to other devs upgrading to React 18?

**Comment by Akshaya-009** [comment]
Thank you for the reply @wadamek65 and @sprasad02. Please update once it is fixed in `version 4`.

**Comment by maslennikov** [comment]
I confirm, with Nextjs 13 and strict mode enabled fields don't get updated when typing (although `onChange` callbacks trigger and model gets updated with setstate properly). Solution from #1289 doesn't work for me. Had to disable strict mode.
