### ISSUE TITLE
findValue() and findField() are removed. How to fetch new values

### ISSUE THREAD

**Issue by knoxgon** [vazco/uniforms#1203]
With uniforms version >= ^2.7 or ^3, the findValue and findField helper props are removed.
The only thing I can find about it is [this release note](https://github.com/vazco/uniforms/blob/master/CHANGELOG.md#v100-rc3-2016-05-20).
I couldn't find any documentation about the replacement. What to use to access other props?

**Comment by knoxgon** [comment]
I don't understand why this is closed...

What do I have to use to get value instead of `findValue` from v.3.1^?

**Comment by radekmie** [comment]
Hi @knoxgon. I see that you removed your comment, but let me cite it here:

> I don't understand why this is closed...

This issue was closed by you, so I marked it as invalid. I'm surprised that you've posted a comment about that, reopened, and closed the issue again.

> What do I have to use to get value instead of `findValue` when those functions are removed?

There's no direct replacement, but almost all of our cases were replaced using `useField`. The rest were true edge cases and required some rearrangement of the component tree.
