### ISSUE TITLE
AutoFields should be in base package

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#136]
currently, all ui-packages (bootstrap, semantic, unstyled) have the same code to render the `<AutoFields />`

This code could be in the base-package. :-)

btw. i'll help with answering the other issues and doing some PR as soon as i have time, sorry for not being not very active at the moment. I will help as soon as i can, you do an awesome work with uniforms here and i would love to help more!

**Comment by radekmie** [comment]
I'd love to do it, but... It's not possible because `AutoFields` renders `AutoField` which cannot be included in the base package because... It renders different fields _(like `TextField`)_ which cannot be included in the base package because of... I think it's quite obvious.

As to your contribution - I really appreciate your commitment! If I could suggest most valuable contribution right now - IMHO it would be the documentation. It's almost 100% complete right now _(few fields components left)_, but it's not the best quality... OK, I'm waiting! :+1:
