### ISSUE TITLE
reset should set initial model

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#140]
I tried reset() for the first time.

It added a button to the QuickForm and called this.reset();.

It thought it would reset the state to the given props.model on the form, but instead, all fields were emptied. Shouldn't it reset to the model instead? if no model is given, then yes, it should empty all fields.

Edit: 

it's on this line:

https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/AutoForm.js#L65

i think it should set it back to this.props.model instead of {},

Setting it back to props.model would be more logical to me, but this would be a breaking change. Opinions?

**Comment by radekmie** [comment]
So you've tried it on `AutoForm` - there's no internal `model` in `QuickForm` :)

Yes, it is a breaking change, but every bugfix is a breaking change because something is working differently now, doesn't it? This should behave exactly the same as the initial state in the `constructor`, so as you've said - `this.props.model` in both `model` and `modelSync`.

Would you like to submit a PR for it?

**Comment by radekmie** [comment]
@macrozone?

**Comment by macrozone** [comment]
@radekmie: Yes, I can do this in the next days. But generally, you do agree with this change?

**Comment by radekmie** [comment]
Yes, I do agree. If you are using it in a fully automatic way _(you have no model)_, then we are not changing anything. If you are using it as a _default_ model, then the new behaviour is the desired one. At last, if you are using it as a managed form, then it's still OK because it'll keep the model from props.

**Comment by radekmie** [comment]
Available in `v1.8.0`.
