### ISSUE TITLE
Support Material-ui?

### ISSUE THREAD

**Issue by thearabbit** [vazco/uniforms#141]
I would like to try `React` with `Meteor`.
But not clear `Bootstrap` vs `Material UI` is better?
Before: `Bootstrap, AutoForm, Tabular...`

**Comment by radekmie** [comment]
_Erm... I can barely understand your issue content, so let's assume that the title is your issue._

Material Design. As in opposite to Semantic or Bootstrap, we have to consider using a React package for it, rather than a CSS package, because of Material Design ripples and other eye-candies. OK, we've got rid of about half of choices. Now we have to choose the React package. We already have an internal `uniforms-material` package, which is using [Material UI](http://www.material-ui.com) components. As I already mentioned in [this](https://forums.meteor.com/t/get-to-know-vazco-uniforms-loo/31836) Meteor forum thread, I can make it public, but... It's not 100% feature-ready. I plan to create a branch with it, so everybody can test it and then make it public.

Questions? Thoughts?

**Comment by thearabbit** [comment]
Thanks for your reply.

**Comment by thearabbit** [comment]
Could I test the `material-ui` branch?

**Comment by radekmie** [comment]
Yes, of course.

**Comment by thearabbit** [comment]
Thanks for your reply, I will test soon.

**Comment by radekmie** [comment]
I think we can close this issue and continue any discussion in #142.

**Comment by thearabbit** [comment]
Excuse, how to install `uniforms-material` in local to test?

**Comment by radekmie** [comment]
There is a step by step guide in the `demo`. You only have to switch to `material-ui` branch.

**Comment by thearabbit** [comment]
Thanks work fine for demo.
but I would use it in my project.

**Comment by radekmie** [comment]
It will be getting finished on Monday, so you can wait a little bit more. If you want to use it now, then you can copy `packages/uniforms-material` to your project and use it as a local dependency.

**Comment by thearabbit** [comment]
waiting you 👍

**Comment by thearabbit** [comment]
Now seen `Ant`, but don't `Material`!

**Comment by radekmie** [comment]
Yes, we had to polish it a little bit more - it's already on master.
