### ISSUE TITLE
value.toISOString is not a function when defaultValue returns a Date

### ISSUE THREAD

**Issue by lmaddio** [vazco/uniforms#146]
`const date = {
type: Date,
label: 'Fecha de creación',
defaultValue: () => new Date()
};
new SimpleSchema({date});`

Returns value.toISOString is not a function error
I wanna make a form with dates and set a default date.
Thanks!

**Comment by radekmie** [comment]
I assume you are using `SimpleSchema@1`. This behaviour is 100% correct - a function is not a valid value of a `type: Date` field. [`SimpleSchema` allows to use functions instead of few fields](https://github.com/aldeed/meteor-simple-schema/blob/v1/simple-schema.js#L835-L841), but `defaultValue` is not one of these - it has to be the exact value, not a getter.

**Comment by lmaddio** [comment]
Thanks!
