### ISSUE TITLE
[question] make findValue() available without connect field

### ISSUE THREAD

**Issue by sakulstra** [vazco/uniforms#159]
I just stepped over props.findValue() and it turns out to be incredible useful! and I wondered if i could use it to resolve some ugliness in my code :)

We currently use a hacky context.model solution to display different submit-button texts dependent on some other fields values. Is it possible to make findValue() available for visual parts of the form without actually using connectField() - as it's not a field.
E.g. sth. like injectGuaranteedProps()?

Best regards,
Lukas

**Comment by radekmie** [comment]
Could you show me an example of our code? I'm not sure if I fully understand your use case. Anyway, you can also create a subclass of `BaseField` and use it's _internal_ methods - take a look [here](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/BaseField.js). I cannot guarantee, that it won't change, so maybe it's not a good solution right now, but this came first to my mind.

**Comment by radekmie** [comment]
@sakulstra

**Comment by sakulstra** [comment]
@radekmie sry for not answering - got distracted by some real issues (as this is basically solvable by context right now).
Anyways I'll try to extract some code where I think providing `.findValue()` would be a benefit:

We currently have a select field which basically allows the user to select the state of a document(published, unpublished,review and stuff like that)
```js
<SelectField
        ref={inputRef}
        onChange={(e, i, v) =>
          onChange(v)
        }
        floatingLabelText="State"
        name={name}
        value={value}
      >
        {_.values(PUBLISH_STATES).map(state => (
          <MenuItem key={state} value={state} primaryText={state} />
        ))}
    </SelectField>
```
As published and unpublished are sensible states which actually affect the user we display hints and warning at some places by basically using context.model

```js
const SomeComp =
  ({ ...props }, { uniforms: { model, onChange, error, state: { disabled } } }) => (
    <Button
      accent
      raised
      type="submit"
      onClick={() => onChange('state', PUBLISH_STATES.DRAFT)}
    >
    {model.state === PUBLISH_STATES.PUBLISHED ?
          'are you sure you want to publish that?!' : null}
    ...
  </Button>
);

SomeComp.contextTypes = BaseField.contextTypes;
```


So this is working, but using contexts feel kind of wrong :D https://facebook.github.io/react/docs/context.html#why-not-to-use-context

Now writing this down, i realized on could write a pretty simple helper hoc to provide context data as prop to make it a bit cleaner at least, but anyway one still hat to use context :)

**Comment by radekmie** [comment]
Which exactly props from [guaranteed props](https://github.com/vazco/uniforms#guaranteed-props) would you like to have? As most of them depend on the field name, the only _usable_ without specifying a name could be `findError`, `findField` and `findValue`. And if you look at the [source](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/BaseField.js#L267-L277) of these methods, you'll see, that your desired HOC is very easy to implement. Therefore, I'm not sure if this should be included in the package but I'll think about it - currently, I'll add it to the [roadmap](https://github.com/vazco/uniforms/projects/1).

---

By the way - how we should name it? I'm sceptic about `withUniforms` _(or something similar)_ because `uniforms` should be written lowercase... Also, `injectGuaranteedProps` is not a good name, because it _can't_ inject _all_ guaranteed props... Ahh, it's a big problem for me!

**Comment by sakulstra** [comment]
I currently use uniforms.onChange and findValue a lot, but you're right - i'm also not sure if this should get into the package as one can easily implement this as a hoc if one really needs it.
