### ISSUE TITLE
"Array.includes is not a function" error on form submit

### ISSUE THREAD

**Issue by Skulmuk** [vazco/uniforms#166]
The above error message appears in my ErrorsField but I get no explanation as to what is failing. I was using an implementation of AutoForm with specified fields (didn't want all my schema shown), so I swapped it for <AutoForm /> just in case it gave me an indication as to what was wrong, but to no avail.

**Comment by serkandurusoy** [comment]
If you are using simpl-schema 2.0 then the root cause and workaround is
here:

https://github.com/aldeed/node-simple-schema/issues/33#issuecomment-269685934




On Jan 18, 2017, at 11:23, Damien Robson <notifications@github.com> wrote:

The above error message appears in my ErrorsField but I get no explanation
as to what is failing. I was using an implementation of AutoForm with
specified fields (didn't want all my schema shown), so I swapped it for
just in case it gave me an indication as to what was wrong, but to no avail.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vazco/uniforms/issues/166>, or mute the thread

**Comment by Skulmuk** [comment]
Thanks, fixed it :)

**Comment by zivkovic** [comment]
When can we expect a proper fix? This would be great:
http://underscorejs.org/#contains

Just a simple search & replace.

**Comment by radekmie** [comment]
@zivkovic wait, what? It's not a problem of this package, but [aldeed/node-simple-schema](https://github.com/aldeed/node-simple-schema).

**Comment by zivkovic** [comment]
Yes, I know, I have also commented on the proper repository, there is a pull already waiting from someone to be accepted...

**Comment by radekmie** [comment]
@zivkovic unfortunately, there is nothing I can do.
