### ISSUE TITLE
Help, please.  How to add custom attribute to field?

### ISSUE THREAD

**Issue by dude-awap** [vazco/uniforms#185]
I do my end-to-end (functional) testing with Cucumber.  Cucumber (like Selenium) can use XPath or CSS selectors on third-party web pages.  When testing one's own code however, it is recommended to select tags for test automation with explicit unique custom attributes, such as `data-cuke="title"` in the example below : 

     <input type="text" data-cuke="title" id="tfid-104-0" name="title" class="form-control" value="">

Up 'til now I have been using [tcomb-form](https://www.npmjs.com/package/tcomb-form), which permits me to do either ...

    title: {
      label: 'Title (custom label)',
      attrs: {
        'data-cuke': 'title'
      }
    },

... or ...

    <button
      data-cuke="save-item" className="btn btn-primary"
      onClick={this.submitForm}>{buttonLabel}
    </button>

**How can I achieve the same thing with Uniforms"?**

**Comment by radekmie** [comment]
All fields are using `filterDOMProps` helper _(or at least should)_, which will leave non-uniforms props untouched, so code like:

```js
<SubmitField data-cuke="save-item" />
```

Should work as expected. If any component is not doing it, then let me know.

**Comment by dude-awap** [comment]
Ok, so I tried with several different fields as you suggest : [Uniforms changes diff](https://github.com/yourse1f-yourorg/mmks/commit/99a5d365b8abc7bfd5469dfd5c62accdbbc7156c)

In only one case did my custom attribute appear ...

    <section class="" data-cuke="save-item">
      <input type="submit" class="btn btn-primary">
    </section>

... and on the section rather than the specific tag, :-(

**Comment by radekmie** [comment]
Well, yes. Although we can't get _a lot_ better because fields like [`ListField` from uniforms-semantic](https://github.com/vazco/uniforms/blob/master/packages/uniforms-semantic/src/ListField.js) are rendering five different elements - it would be an overkill to allow settings props for each of it. I see two solutions: either leave it as it is now _(it's not a big problem to have a select element like `[data-cuke="save-item"] > input`)_ or if you _really_ want to have a direct selector, you can create a custom field.

**Comment by dude-awap** [comment]
I would happily create a custom field, if I could understand how.  Are you suggesting to subclass the unstyled TextField's [input tag](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/TextField.js#L24), and then add attributes to it like this : 

    document.getElementsByTagName("input")[0].setAttribute("data-cuke", "title");    

... or are you suggesting cloning TextField.js to CukeTextField.js and adding the attribute directly?

Would it be possible for you to add a paragraph to the `README.md` that explains how to customise a field with non-standard attributes?

**Comment by radekmie** [comment]
There is no need for a separate section with components with non-standard attributes because those are just like every other attribute. Copying every field _is_ a solution, but it's not future proof. Altering DOM in the way you've suggested is not a good idea in React world.

If you really need it now, either use combined selectors, like `[data-cuke="save-item"] > input` or create custom fields. I'll give it some time, maybe I'll find a better solution - we have `inputRef`, why not `inputProps` - but let's think about it some more.

**Comment by dude-awap** [comment]
I now have my Cucumber tests working against a Uniforms page, using slightly more complex XPath, as you suggest.  Eg, ....

   ' //div[@data-cuke="content"]/*/textarea'

... so I can get by without a more direct route.

I do believe, however, that custom attributes are an important part of any HTML forms toolkit.

**Comment by radekmie** [comment]
Yes, of course they are, but, as I said before, there are components which are rendering five or even more DOM elements and I don't want to have separate prop for each of them.

**Comment by janowsiany** [comment]
#

**Comment by radekmie** [comment]
It doesn't make sense in `uniforms-antd` or `uniforms-material` because we are not rendering whole DOM there. Thus it will create a gap between theme packages. As a solution, I suggest using direct props, like `<AutoField {...} data-test="..." />` and targeting desired component differently in each theme - it should work everywhere. If some components are not working this way, please file another issue.
