### ISSUE TITLE
Set time zone for AutoForm DateField

### ISSUE THREAD

**Issue by JWDobken** [vazco/uniforms#190]
With DateField, the shown time with `new Date` seems to be one hour earlier than the time of the host.
Host is at UTC+01:00, so that could be the reason.

However, when I `console.log` on submit the date is given in my timezone:

    Object
        createdAt: Sat Feb 11 2017 11:26:02 GMT+0100 (CET)

So, is it possible to control the shown date in AutoField/DateField?

**MWE**

I have the following simpl-schema:

    const Activities = new Mongo.Collection('activities');
    Activities.schema = new SimpleSchema({
        createdAt: {
            type: Date
        },
    });

Then the application code, this is the autoform:

    <AutoForm
        schema={Activities._collection.simpleSchema()}
        onSubmit={doc =>console.log(doc)}
        model={{
            startedAt: new Date()
        }} >
        <DateField name='startedAt' label='Start activity at:' />
        <SubmitField value='Insert Activity' />
      </AutoForm>

**Comment by radekmie** [comment]
Which theme?

**Comment by JWDobken** [comment]
'uniforms-bootstrap3'

**Comment by radekmie** [comment]
OK. As you can see, `DateField` in `uniforms-bootstrap3` is [just an input](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap3/src/DateField.js) - there is nothing more. If [this](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap3/src/DateField.js#L7) is not, what you expect, then we might add an option to provide custom `dateFormat` function.

**Comment by JWDobken** [comment]
So I can change the input indeed like

    var d = new Date();
    d = new Date(d.setHours(d.getHours() + 1))
    ...
        startedAt: d
    ...
    

And than modify the output, but this is not elegant at all.

Do I understand correct that you offer to include some functionality?

**Comment by radekmie** [comment]
I won't include time zones related functionalities. If you want, we can introduce prop like `dateFormat` to override the default one.

**Comment by JWDobken** [comment]
Ah I get what you mean.
overriding the `dateFormat` prop would indeed be a better solution for me.
Is it also possible to implement the `timeFormat='24hr'` for bootstrap3?

**Comment by radekmie** [comment]
It is, but it would require to include a time formatting library... I think, that `dateFormat` will be enough - you can use any library you want.

**Comment by serkandurusoy** [comment]
I would suggest introducing a transform prop/function along with a
dateformat prop would be ideal because dates almost always need to be
displayed in a different time zone for some feature or another. A transform
function would allow for that and many other use cases. Format on the other
hand is a "gimmick" to that functionality, but still would be very valuable
for display usecases.

**Comment by radekmie** [comment]
How exactly should the 'transform' function work?

**Comment by serkandurusoy** [comment]
take in a date and return a date

especially things like setting things to midnight, setting time to nearest
hour, setting a different timezone etc or similar use cases can benefit
from this. granted, this can already be done with a form model change
handler or a custom component.

now that we're thinking about it, perhaps a transform prop can be provided
by connectField so that all components can benefit from this

Sent from my iPhone



On Feb 11, 2017, at 16:36, "Radosław Miernik" <notifications@github.com>
wrote:

How exactly should the 'transform' function work?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/vazco/uniforms/issues/190#issuecomment-279144239>, or mute
the thread

**Comment by radekmie** [comment]
But _when_ exactly should it be run?
* _To_ the field: simply change your `model`.
* _From_ the field: simply change your `onChange` or `onSubmit`.

I don't see a really use case for it.

@JWDobken - I'll add `dateFormat` soon.

**Comment by radekmie** [comment]
Okay, I've spent some time with it and here is the result:
* We can't add `dateFormat` function, because `<input type="datetime-local" />` have a fixed format.
* We don't have to add `transform` prop - there is `modelTransform` prop on every form - you can use it to fix timezone and so on.

I'll close it as it is answered, but feel free to ask.

**Comment by serkandurusoy** [comment]
The problem with a model transform is it feels more like a hack to me
because it is away from the field and on the form level. If I wanted to do
something that is specific to the overall state of the model, model
transforrm is great, and I do use it extensively. But for things that are
really confined in a single field, I don't think model transform is elegant
at all.

On Sun, Feb 12, 2017 at 10:48 PM, Radosław Miernik <notifications@github.com
