### ISSUE TITLE
Better automatic (passed through) options for a select, radio, checkboxes

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/uniforms#23]
For example, here's a standard Enum based "select" field with `allowedValues` & `autoform.options`

```js
{ ...
  fileType: {
    type: Number,
    label: 'File Type (Upload, processing, tmp, log, etc)',
    optional: true,
    allowedValues: Enums.Buckets.fileTypes.values(),
    autoform: {
      options: Enums.Buckets.fileTypes.options(),
    },
  },
... }
```

I have this functionality somewhere -- I'll see if I can dig it up...

**Comment by radekmie** [comment]
Currently, props can be declared in SimpleSchema ([it's covered here](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/bridges/SimpleSchemaBridge.js#L122-L137)) within `uniforms` key.

Idea:

```js
{ ...
  fileType: {
    type: Number,
    label: 'File Type (Upload, processing, tmp, log, etc)',
    optional: true,
    allowedValues: Enums.Buckets.fileTypes.values(),
    uniforms: {
      options: Enums.Buckets.fileTypes.options(),
    },
  },
... }
```

_Yes, I've just changed `autoform` to `uniforms`._

But to keep compatibility with existing `SelectField` components, it will be interpreted as:

```js
if (_.isObject(options)) {
    options = Object.keys(options).map(label => ({label, value: options[label]}));
}

transform = value => options.find(option => option.value === value);
```

So it will be easier to transition from `aldeed:autoforms` to `uniforms` and create another `SelectField` components, without special logic.

What do you think, @zeroasterisk?

**Comment by zeroasterisk** [comment]
I think that sounds fine... 

For ease of use, for people migrating from `aldeed:autoforms` to `uniforms` I think supporting [whatever they support](https://github.com/aldeed/meteor-autoform#what-are-the-various-ways-i-can-specify-options-for-a-select-radio-group-or-checkbox-group) would be ideal, but limited scope is reasonable.  _(omitting helpers support)_

I also think it (and all ported config) should be a cascading config:

pseudocode: `options = uniforms.options || autoform.options || undefined`

**Comment by radekmie** [comment]
I thought about allowing `autoforms` key in schema (with some warnings), but it should be discussed. If you really need it - create another issue and let's discuss it.

**Comment by serkandurusoy** [comment]
I think naming consistency is important. If we are using the component as `<AutoForm ..../>` then the corresponding key on the schema should be the same. If we use uniforms on the schema, then we should probably name the component <UniForms   ... />

**Comment by radekmie** [comment]
@serkandurusoy: `<UniForm />`?

Ha, I thought the same at the beginning! But if you are _new_ and want to know, what each form is doing... What `<UniForm ... />` or `<Uniform ... />` is doing, while there are `<BaseForm ... />`, `<QuickForm ... />` and other, _well named_ ones?

**Comment by serkandurusoy** [comment]
I don't see an example that uses anything other than AutoForm, so why not call it Uniform:

```js
// These are equivalent:

const FullAutoForm = () =>
    <AutoForm schema={PostSchema} onSubmit={doc => console.log(doc)} />
;

const SemiAutoForm = () =>
    <AutoForm schema={PostSchema} onSubmit={doc => console.log(doc)}>
        <AutoField name="category" />
        <AutoField name="authors" />
        <AutoField name="publishedDate" />
        <AutoField name="published" />
        <ErrorsField />
        <SubmitField />
    </AutoForm>
;

const ExplicitAutoForm = () =>
    <AutoForm schema={PostSchema} onSubmit={doc => console.log(doc)}>
        <SelectField name="category" />
        <ListField name="authors">
            <ListItemField name="$">
                <NestField>
                    <TextField name="name" />
                    <NumField  name="age" />
                </NestField>
            </ListItemField>
        </ListField>
        <DateField name="publishedDate" />
        <BoolField name="published" />
        <ErrorsField />
        <SubmitField />
    </AutoForm>
;
```

I believe quickform is just redundant and should not be used. Baseform is a "developer" friendly component that should be used to creat custom top level form components. and UniForm should be our official top level component "implementation" and not be named autoform

**Comment by radekmie** [comment]
Yes, that would make sense if `uniforms` would be Meteor-only packages, but they're not. I'm a fan of semantic naming, so every form component is named after his role.

Yes, those _intermediate_ forms are mostly unused, but in my first draft were only `Base`, `Quick` and `Validated` forms - `Auto` is just a _helper_, that is the easiest to use _(that's why others are described only on inheritance graph)_.

**Comment by serkandurusoy** [comment]
Ok, then the question is, what's your suggested best practice? Do you
suggest that we use quickform, validatedform etc?

Using helper/shorthand names is not always a great thing due to the
abstraction it creates.

But if the separate components don't offer much value out of the context of
Meteor, than perhaps we should document this and the usecases.

(Now that I'm thinking about the docs site and examples, I think we should
hear more about your reasonings behind your choices anyway)

**Comment by radekmie** [comment]
Use whether you need, really.

About other forms... In short _(I want to write more about it in the documentation, or maybe in some Medium post...)_ - every `*Form` (without `BaseForm`) exposes a static method called `*` (`Quick` for `QuickForm`, etc.). It can be used to _extend_ functionality of given component [_(look at `ValidatedQuickForm` source!)_](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/ValidatedQuickForm.js#L5). That's why they are completely separated.

**Comment by zeroasterisk** [comment]
Thanks @radekmie -- so to use this, it should be a simple as changing `autoform.options` to `uniforms.options` in my schema, right?

**Comment by radekmie** [comment]
Yes.
