### ISSUE TITLE
Radio-Field should use transform-property to display the value

### ISSUE THREAD

**Issue by macrozone** [vazco/uniforms#24]
Hi there, awesome work so far, looks really promising and clean!

I found one oddity, though: In all RadioField-Variants, the value is displayed directly :

` <label>{item}</label>`

I think it should be: ` <label>{transform(item)}</label>` with `transform` beeing a prop passed to the field.

I would do a PR, but i wanted to ask, if I understand this right?

**Comment by serkandurusoy** [comment]
That indeed looks like an overside.

You can take cue from the select component as a proper example and
implement a PR that also covers the styled components.

Thanks!

Sent from my iPhone



On Jun 14, 2016, at 15:59, Marco Wettstein <notifications@github.com> wrote:

Hi there, awesome work so far, looks really promising and clean!

I found one oddity, though: In all RadioField-Variants, the value is
displayed directly :

<label>{item}</label>

I think it should be: <label>{transform(item)}</label> with transform
beeing a prop passed to the field.

I would do a PR, but i wanted to ask, if I understand this right?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vazco/uniforms/issues/24>, or mute the thread
<https://github.com/notifications/unsubscribe/AEbz3LIyuWqVoMyI0IClSKEmgQu-lcExks5qLqXHgaJpZM4I1Szi>
.

**Comment by radekmie** [comment]
Yes, that's a good idea, @serkandurusoy. Looking forward your PR, @macrozone!

**Comment by macrozone** [comment]
Ok here we go. 

I noticed that the published version does not include the transform-mechanism at all. Are there other tasks to do before the next release?

**Comment by radekmie** [comment]
No, but currently releases are quite random - sorry.

**Comment by radekmie** [comment]
I've just released `1.0.0-rc.16`.

**Comment by macrozone** [comment]
awesome, thx guys!
