### ISSUE TITLE
basic use documentation for Array list types

### ISSUE THREAD

**Issue by ericmcgregor** [vazco/uniforms#257]
This seems like a great library, and i'm looking forward to figuring out how to use it, but I've really been stumped by the documentation.  I'm struggling to clearly understand and apply some basic things.

I have a schema that users an array of keywords.  I would imagine that this would allow me to edit those keywords and ad new ones.  but the default seems to just be an empty box?  

How does one change the default Array fieldType to ListAddField?  And are there any places where common use cases can be seen or demoed?  the documentation here is really tough to follow.

**Comment by ericmcgregor** [comment]
Yea, i'm at a complete loss to find an example of how you could modify the default fieldtypes functionally.  the documentation is really extensive, but i almost can't do anything with it.  

you have an autofield algorthm with a fieldType function as part of it's api... but how does that work?    does this get defined in the schema?  are there any examples out there of how to actually implement this package?

**Comment by ericmcgregor** [comment]
Ok, after about two hours of struggling here, you win.  Some basic use cases would be really helpful.  I have an array, and i would like to modify the default form field to include the add and remove button as well as list out a minimum number of items.  I would like to use the AutoForm component to do this without rebuilding the entire form using components.  Clearly i'm not comprehending the documentation here.  No question it's in there somewhere, it looks like every function is documented, but i can't see any path to being able to understand how to pull it together.  sorry if i'm frustrated here, but it just makes me feel really stupid getting stuck on literally the first thing i wanted to do.

**Comment by radekmie** [comment]
Hey @ericmcgregor. I've tried to make the documentation as explanatory as I could, but it seems to be not enough if you are not deeply into this package. I'll focus on it in the closest future.

Now, let's answer your questions:
* When you have a field in your schema _(I don't know, what schema and theme are we talking about)_, then it will render as a `ListField`. What is it?

```js
<ListField name="keywords" />

// It is basically expanded to something like this
<ListField name="keywords">
    <ListAddField name="$" />
    <ListItemField name="1">
        <AutoField />
        <ListDelField />
    </ListItemField>
    <ListItemField name="2">
        <AutoField />
        <ListDelField />
    </ListItemField>
    // ...
</ListField>
```

What does this mean for you? It renders `ListAddField` somewhere at the top level, which will add new items and `ListItemField` for each item in the array. What about `ListDelField`? It's inside of `ListItemField`, to delete this very item.

Why it's an empty box? I guess because your array is empty, but I can't say more without an example.

* Demo? There is one, at [uniforms.tools](https://uniforms.tools/). It's linked in the readme.

* _How you could modify the default field types functionally?_ Basically, you can't. Each field has its own role and if you need a custom field, then create one, either from the scratch or from built-in one.

* > you have an autofield algorthm with a fieldType function as part of it's api... but how does that work? does this get defined in the schema? are there any examples out there of how to actually implement this package?

I don't get it.

---

All in all, as you've already said: _it looks like every function is documented, but I can't see any path to being able to understand how to pull it together_. Yes, it's true.

I want to build/write a tutorial, which will describe the most common problems, step by step, so everybody could create own field, form and theme.

If something is still not clear, ask.

**Comment by ericmcgregor** [comment]
this uniforms.tools link is exactly what i needed to make sense of some things.  I'm not sure how i missed it, i guess i didn't see it in the links next to documentation.  :(

the other thing that was confusing me was my array form was not showing the + button because it was rending it using the class octicon.  i guess i need to install those.  So, i just couldn't figure out why i didn't have a + button and thought i needed to somehow specify that as a parameter.

**Comment by radekmie** [comment]
Good. I'll close it then, as it's already clear. About the documentation/tutorial: it's the main goal now.

**Comment by ericmcgregor** [comment]
wait... "octicons"?  is this covered in the documentation anywhere?  all of this confusion was actually due to the fact that the "octicons" aren't rendering out of the box.  that's why i couldn't see the + or - icons.  Do you have to do something special here?  i guess i'm the only person this doesn't work for.

**Comment by radekmie** [comment]
We can ask @zeroasterisk, as he is the author of both Bootstrap packages. As I've looked into the [docs](https://v4-alpha.getbootstrap.com/migration/#components):
> Dropped the Glyphicons icon font. If you need icons, some options are:
> * the upstream version of Glyphicons
> * Octicons
> * Font Awesome
I guess it's a sane choice.
