### ISSUE TITLE
Inline Validation

### ISSUE THREAD

**Issue by LucasBadico** [vazco/uniforms#272]
Hey guys, I`m integrating the  Uniforms on my project, with simplschema2.

But I`m facing a issue with the  inline erros and onchange validation. When one field is opt to validate the entiry schema is validated as well so all fields are being show as error... how fix that?

**Comment by radekmie** [comment]
Hey, @LucasBadico! If I got you correctly, you want to validate form field by field, right? If so, unfortunately, it's impossible _(why? ask, I'll elaborate on it)_. If you want to only display the error of changed fields, then you have to create custom fields - it's not _(and won't be)_ implemented in the standard themes.

**Comment by LucasBadico** [comment]
Please elaborate, so with custom fields I can archieve that? need to do that

**Comment by radekmie** [comment]
1. Why is it impossible to validate form field by field?
Because most _(every single I know)_ schemas _(including all integrated with uniforms)_ allows validators to depend on other fields. Example? Date range picker with a sanity check of _start before end_ and _end after start_. Now, if you want to validate only one, then this validation will fail. It's OK because it's intended in this case _(no date is not after/before any other, right?)_, but it's not in others - like inter-collections integrity and others.

2. Custom fields with such functionality.
You can achieve it in... Well, many different ways. The simplest one I see is that you can wrap every field and do not pass it its error if it hasn't changed _(these props are [guaranteed](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#guaranteed-props))_. Another one is very similar, but it can be triggered on blur _(or focus or whatever)_. Problem? Well, in this case, you won't show a _this field is required_ error, which might cause at leas some confusion. Other ways? Of course, many of them - just think out one fitted to your needs and do it.

If you'll need some additional help on this - search for it in other issues, ask for it on [Gitter](https://gitter.im/vazco/uniforms) or file another issue if needed.

**Comment by LucasBadico** [comment]
Thanks, again... totaly get why is impossible... I will try the simplest one.
