### ISSUE TITLE
skip validation for internal list field item

### ISSUE THREAD

**Issue by cesarve77** [vazco/uniforms#283]
Sorry for my english and thanks for this great package

For reproduce this bug go to:
[https://uniforms.tools/](https://uniforms.tools/)

replace schema  field with:
```javscript
new SimpleSchema({
    "arrayOfString": {"type": Array, "minCount": 2},
    "arrayOfString.$": {"type": String, "min": 1 , "max": 140},
})
```

and submit the form of right side.

Expected behavior: show error for arrayOfString as required and/or show min length for children

**Comment by radekmie** [comment]
Thanks for the report - I'll get to it later.

**Comment by cesarve77** [comment]
I write this If somebody is passing thru this, Is a bug you can skip it just creating a object inside the array: like:

new SimpleSchema({
    "arrayOfString": {"type": Array, "minCount": 2},
    "arrayOfString.$": {"type": Object},
    "arrayOfString.$.value": {"type": String, "min": 1 , "max": 140},
})

**Comment by radekmie** [comment]
I still didn't figure it out, but here's a small update: it's caused by SimpleSchema validation model. In uniforms, if a field is empty, then `undefined` is used. SimpleSchema check, if every constraint pass, so `minCount: N` require N elements - therefore `[undefined, undefined, ..., undefined]` is passing the validation - it's not even modified by `.clean`**!** Now I'm working on how to get this working, but it has to be on the schema side because it's not a problem with uniforms directly.

**Comment by radekmie** [comment]
Hey, @cesarve77. As I've said earlier - it's a problem with SimpleSchema, but **only** with the Meteor one. If you'll try it with [`simpl-schema`](https://github.com/aldeed/node-simple-schema) then it's working as expected.
