### ISSUE TITLE
Additional validators/types

### ISSUE THREAD

**Issue by aleksandrenko** [vazco/uniforms#288]
Hi, great project. Happy to find it. 
There are some things missing for my taste.
I guess some additional validators/fields would be very helpful and push the project further as a more detail solution for forms.

I suggest to add fields (text or other with custom default validator)
GeoLocation (lat/lng)
Email
Credit Card
Phone
Field with options for enum
Url
Range
Color
File
Integer
Float
Timezone
Password
Time
DateTime
Date

**Comment by radekmie** [comment]
Hey, @aleksandrenko. In any case, I won't add any validation logic to this package - that's what schemas are for. Most of fields you've described are currently achievable - for example, for email and phone you can use HTML5 input types, for _enum_ field, simple select will do... For others, like geolocation, combining two or more fields will suffice. The other point is that the main goal is to provide a general solution for handling forms with a set of fields, which will be able to render any form - not to render it in a way, that is best for UX - it's your job. That's why creating new fields is so easy - because you'll create a lot of them.

**Comment by aleksandrenko** [comment]
This would be true if the main purpose of this package was not to auto create form and fields based on schema. If i'm going to create the fields myself what is the point?

**Comment by radekmie** [comment]
The point is that you already have a complete logic _glueing_ any schema to any field you'll ever write.
