### ISSUE TITLE
selectField: allowedvalues, optional:true incompatible

### ISSUE THREAD

**Issue by ggerber** [vazco/uniforms#300]
Hi,
Uniforms is fantastic. I picked up the following issue using uniforms-bootstrap4 and node-simple-schema.
Uniforms shows a validation error when using a selectField with a property that is optional and has allowedValues set. There is no validation error when the property is required.
I think it has to do with the fact that when the property is optional the selectField adds a default option to the selection list with a name equal to the property. This default option cannot be found in the allowedValues list, so uniforms issues a validation error

**Comment by radekmie** [comment]
Could you post a schema to reproduce it? I'm not 100% sure that I understand this issue correctly.

**Comment by ggerber** [comment]
Apologies, I cant reproduce the problem with the code below.
Question: Is it the correct behaviour to return an empty string "" when optional=true and selecting the inserted "Test" option?

import SimpleSchema from 'simpl-schema';
import SelectField   from 'uniforms-bootstrap4/SelectField';
const allowedValues = [
  "a",
  "b",
  "c"
];
model = { test: 'a' }
const schema = new SimpleSchema({
  test: { type: String, allowedValues, optional:true  }
});
const exampleForm =
<AutoForm
  showInlineError={true}
  onSubmit={(test) => {console.log('test',test)}}
  schema={schema}
  model={model}>

    <SelectField name='test' />

    <SubmitField />
</AutoForm>;

**Comment by radekmie** [comment]
Well... Yes and no. Yes because SimpleSchema remove empty strings by default. No because it should remove it completely. I'll think about it and let you know.

**Comment by radekmie** [comment]
OK, it took me a while. Yes - it should return an empty string. Why? We have two scenarios: either your `allowedValues` includes an empty string, then it's a problem, but I cannot find a case for it right now _(let me know if it's a problem for you)_ or you can easily ignore it (in SimpleSchema, `.clean` will remove it by default).

A bit more detailed answer: how (on the component level) can we decide, if the `<select>` empty value is one of the options or our _empty marker_? We simply can't. What options do we have? For example setting an _unique marker_, like, long random string _(and make sure that it's not in `allowedValues`!)_. It's simply inefficient (we have to do it every render, because `allowedValues` may change over time) and over-engineered.
