### ISSUE TITLE
npm WARN uniforms@1.20.0 requires a peer of simpl-schema@>=0.0.4 < 1.0.0 but none was installed.

### ISSUE THREAD

**Issue by cesarve77** [vazco/uniforms#334]
First, congratulation again for this great package.

I get this warning

`npm WARN uniforms@1.20.0 requires a peer of simpl-schema@>=0.0.4 < 1.0.0 but none was installed.
`

I'm not using simpl-schema I will use graphql

If i have to install simpl-schema anyway it will be good to change the documentation

**Comment by radekmie** [comment]
Thank you, @cesarve77! It was said many times: this is a peer dependency - not a hard dependency. It's needed, because otherwise uniforms can't ensure (in a _good_ way) if related packages have a good version. Of course, npm offers `optionalDependencies`, but these are installed by default and we don't want it to.

_(I have to add it to a FAQ or something)_
