### ISSUE TITLE
Field values get preset to empty object for SimpleSchema field with type Object

### ISSUE THREAD

**Issue by pozylon** [vazco/uniforms#382]
Problem: Value is initially {} instead of null/undefined

Actual: For a field that is type=Object + required=true, the "required" validation does not fail on the field itself.

Expected: For a field that is type=Object + required=true, the "required" validation fails unless the value has been set to any valid object by setting the value of the object field or any child field values.

This leads to the following use case which is not possible to implement right now with a pure required validation setup:
"The whole address field-set is optional unless somebody fills out one of the following fields: address.street, address.city, address.line1"

Schema:

```
new SimpleSchema({
     notOkayCase: {
        type: Object,
        blackbox: true,
        required: true,
      },
      notOkayCaseTwo: {
        type: Object,
        blackbox: true,
        required: true,
      },
      'notOkayCaseTwo.a': {
        type: String,
        required: false,
      },
      'notOkayCaseTwo.b': {
        type: String,
        required: false,
        vi: { fieldid: 'b' },
      },
      okayCase: {
        type: Object,
        required: false,
      },
      'okayCase.a': {
        type: String,
        required: true,
      },
      'okayCase.b': {
        type: String,
        required: true,
      },
})
```

I use the Simple Schema 2 Bridge.

**Comment by radekmie** [comment]
Hi @pozylon.

> Problem: Value is initially {} instead of null/undefined

It is only, when you are using `connectField` (or a field created with it), the field is required and no `initialValue` is being set. It's important, as you could use `null` as `initialValue`, but it'll break your nested fields: `get({x: null}, 'x.y') === null`, therefore `ensureValue` won't work and you'll see the (un)controlled input warning.

> Actual: For a field that is type=Object + required=true, the "required" validation does not fail on the field itself.
> Expected: For a field that is type=Object + required=true, the "required" validation fails unless the value has been set to any valid object by setting the value of the object field or any child field values.

Not really. The `required` will fail if there's no value, not a correct one (full logic [here](https://github.com/aldeed/simple-schema-js/blob/dcfb888501389a6731d2d7a29683ab2094f448a8/package/lib/validation/requiredValidator.js#L5-L12)). Anyway, I got your point.

> This leads to the following use case which is not possible to implement right now with a pure required validation setup:
> "The whole address field-set is optional unless somebody fills out one of the following fields: address.street, address.city, address.line1"

Let's assume, that we'll change it and object fields won't be initialized. Then if I'll enter anything in `address.street`, then the model becomes `{address: {street: 'blah'}}`. What if I remove it? It'll be `{address: {street: ''}}`. Then, `.clean()` will trim it (it's the default behaviour but only for non-`blackbox` objects), so `{address: {}}`. It's still an invalid model.

Maybe it wasn't a wise choice (yep, it's a design decision, not a _bug_ bug), but it still makes far more sense in most cases. In your, I see two simple options:
* add `custom` validation where an empty object leads to a `required` error,
* create a custom field, which will unset its value (i.e. set `undefined`; look above for why not `null`).

The first one is fairly easy and very common. Also, it may be even better, if you are using it not only for the form validation but also for your API - an empty object shouldn't pass the validation, right?

---

It turned out to be quite a lot of text. Did I answered your question? :confused:

**Comment by pozylon** [comment]
@radekmie Thank you very much for bringing us uniforms (amazing work!) and that detailed explanation, I see your point with the clean() and right now I'm using "custom" to enforce my use case, so that basically fixes my issue.

I think It could help to document the object handling logic in the readme or just reference your explanation above from there, as aldeed's autoform is further cleaning empty objects in the "{address: {street: ''}}" case enabling the address use-case: http://autoform.meteorapp.com/quickform -> playground -> select "Object field"

So people migrating from autoforms to uniforms reusing the same schemas could go weirdo like me in that case :)

**Comment by radekmie** [comment]
Well, `autoforms` were _easier_ (simpler?), as it worked only with SimpleSchema - here it's not the case, as I don't know, which schema will it be. There's more - I don't know if it'll be validated at all (see `JSONSchemaBridge` as an example).

About the documentation... I know, I really know that. Shame on me, but I cannot get myself to do it. It'd be great if you'd add this to #259. One day, someone will (hopefully) get to it and all listed things will be written... Somewhere.

---

I understand it's all clear, so I'm closing.
