### ISSUE TITLE
How to do i18n right?

### ISSUE THREAD

**Issue by Floriferous** [vazco/uniforms#464]
From what I can see, the labels should be defined on the schema to work with `AutoForm`. 

But I happen to use `react-intl` to translate everything, how should I proceed to easily use `AutoForm` without adding the translation on my simple-schema ?

**Comment by radekmie** [comment]
Hi @Floriferous. In general, there are few ways to do so, depending on the level of abstraction you want to do it - schema, field or `AutoField` component.

When it comes to the `simpl-schema`, you can use `uniforms: {...}` (an object) to pass extra props the field, but `uniforms: () => ({...})` (a function returning it) is also accepted. With it, dynamic labels can be fetched from any source.

On the field level, you can prepare your own component set, when instead of `{label}` you'll use `<Translate>{label}</Translate>` (or any logic, depending on your i18n package).

While the first one is schema-dependent and the second is theme-dependent, there's an additional option, somewhere in between. You can create a custom `AutoField` component, [based on a builtin one](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/AutoField.js), where you provide some additional props and `label` might be one of them (based on other props, like `name` or some schema field).

**Comment by Floriferous** [comment]
Alright, and how would you modify `AutoForm` itself?

Ideally I'd want to be able to do:

```js
<AutoForm
  schema={TodoSchema}
  model={todo}
  onSubmit={someUpdateFunc}
  overrideFieldLabel={field => <Translate>{field.id}</Translate>}
/>
```

I feel like I'm going to have to either:
1) Modify all my schemas and add tons of excess code on every field with the `uniforms` key,
2) Override all of the individual Field components (including nested behavior and `allowedValues` support).

Your last suggestion appeals the most to me, but it's still unclear how to me how I can ever use `AutoForm` if I customize `AutoField`, which I think I should use in... `ValidatedForm`? I can't wrap my head around it from the docs.

I really like the simplicity of `AutoForm` and would like to keep using it without heavily modding it.

**Comment by radekmie** [comment]
You forgot about the second argument to `connectField`, especially `includeInChain: false`.

**Comment by radekmie** [comment]
_Nested_ in terms of the tree, not the schema:

```js
<AutoField>
    <XField> // Nested.
```

**Comment by Floriferous** [comment]
Got it. So how do you detect whther a field is nested in the schema, and get a nested name?

If I have `myFieldArray.$.description` In my simple schema, how could I get the name of that field in autoform to be `myField.description`?

Should I create a custom array field?

**Comment by radekmie** [comment]
I don't really get it. Anyway, I think we are a bit off the topic now. If it's clear, how to do i18n - let's close it. If you want to talk more about that, we can either discuss it on Gitter or in a separate issue.

**Comment by radekmie** [comment]
As the main issue is already solved, I'm closing. In case of additional problems (or need of more explanation), please create another issue.
