### ISSUE TITLE
SelectField option values as Number

### ISSUE THREAD

**Issue by mgscreativa** [vazco/uniforms#468]
Hi! I created this select field in my form with Number values

```
           <SelectField
              name="state"
              label="Published"
              options={[
                { label: 'Unpublished', value: 0 },
                { label: 'Published', value: 1 },
              ]}
            />
```
I need the SelectField value as Number, but on submit I get `data.state: "1"`, the field got converted into string.

Is there a way I can tell SelectField that it's values are Number instead of String?

Thanks!

**Comment by radekmie** [comment]
Hi @mgscreativa. It's because React renders `<select>` as a native HTML element and the value gets stringified - themes like AntD do it for you. In this situation, you can either:
* create a custom field with a transformation (or somehow picking the _real_ value of the `<select>`), or,
* use `modelTransform` to do so on the form level.

Preferably, creating custom fields is the _better_ option. It'll also help with handling more complex scenarios, like a select of object values.

**Comment by mgscreativa** [comment]
Great! I just parseInt in the submit handler function as it's not big deal

**Comment by mgscreativa** [comment]
For the record, the uniforms way of doing this as sugested by @radekmie should be:
```
    <AutoForm
      schema={YourSchemma}
      model={yourModel}
      ...
      ...
      modelTransform={(mode, model) => {
        if (mode === 'submit' || mode === 'validate') {
          const newModel = {
            ...model,
            state: parseInt(model.state, 10),
          };

          return newModel;
        }

        return model;
      }}
    />
```

**Comment by radekmie** [comment]
Not really, I'd rather create a custom component.
