### ISSUE TITLE
Numeric input behaves strange in Safari

### ISSUE THREAD

**Issue by adrianschneider94** [vazco/uniforms#558]
Hi there, great package!

My issue are the numeric inputs (all packages except ant):
In Safari (and according to the HTML Standards) is target.value of the onChange-Event undefined, if the validation (HTML-standard) of the string fails.
This leads to the fact, that you can enter all letters (e.g. '8$%&') into the input field, but you won't get an error of the validator, as uniforms converts it in 'undefined'.

I've built a custom field based on cleave.js for my project which resolves the issue -- I think cleave.js could be useful for some other fields in uniforms.

Best wishes
Adrian Schneider

**Comment by radekmie** [comment]
Hi @adrianschneider94. I'm aware of that. That is because each `NumField` (except the one in `uniforms-antd`) have an [internal class ](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/NumField.js#L41-L80) to fix numeric inputs handling in React < 16. There's even a comment to make it optional and I think that it's getting more and more important.

Just for the record - we won't use any external package for that, simply delegate it to React (but still try to do our best in older versions).

**Comment by radekmie** [comment]
I've prepared a possible solution on [`adaptive-num-field`](https://github.com/vazco/uniforms/tree/adaptive-num-field) branch. Will let you know after some inhouse tests.
