### ISSUE TITLE
Number fields are defaulted to either min or max values from schema, even when optional

### ISSUE THREAD

**Issue by todda00** [vazco/uniforms#58]
When using a schema definition with either min, max, or both, the field is defaulted to either the min (if min is present), max (if only max is present). This is true for schema definitions where optional : true as well. This situation occurs for both TextField and NumField.

I would expect to see a blank field instead of defaulting to either min or max, especially for an optional field.

Example code and output:

```
...
  'height.feet':{
    type: Number,
    optional: true,
    min: 4,
    max: 8
  },
  'height.inches':{
    type: Number,
    optional: true,
    max: 11
  },
...
```

```
            <div className='col-xs-12 col-md-4'>
              <TextField name='height.feet' placeholder='Feet' label='Height - Feet' />
            </div>
            <div className='col-xs-12 col-md-4'>
              <TextField name='height.inches' placeholder='Inches' label="Height - Inches" />
            </div>
```

Result:
![localhost_3005_register_player_athletics](https://cloud.githubusercontent.com/assets/8363924/16494797/b0a94c20-3eb8-11e6-98df-75e535aa8671.png)

**Comment by radekmie** [comment]
It shouldn't happen with `optional` fields - that's a bug.

---

Yes, [current implementation of `SimpleSchemaBridge#getInitialValue`](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/bridges/SimpleSchemaBridge.js#L114-L140) gets into account `min` and `max`. If you think that's not a good idea, please leave a comment here.

**Comment by todda00** [comment]
Behavior definitely needs to be changed for optional fields, but I also think its strange to set an initial value even when required. In my opinion you want to force the user to input a value, not default to either the max or min. 

If someone wants a default, they can set the model.

**Comment by radekmie** [comment]
Yep, I've fixed behaviour of optional fields, but I'm still thinking about those `max` and `min`... You have a point there - everybody can provide a `default` value in the model, but is that "any initial value possible" _rule_ bad? It's hard to decide (at least for me), if a blank input is better than `min` or `max` (but the `min` seems to be more reasonable than the `max`).

**Comment by serkandurusoy** [comment]
This has not been fixed for me with rc.23

**Comment by radekmie** [comment]
You mean `max` and `min`, @serkandurusoy? If so, yes - it's not implemented, because I don't know if this would be a _good change_ (as I said one comment above). If you meant `optional` fields, then, well - it should.

**Comment by serkandurusoy** [comment]
Yes, I have an optional: true field with a max value (no default, no min)
and it shows the max as an initial value when form is rendered.

```js
budget: {
    type: Number,
    max: 2147483647,
    optional: true,
  }
```

Regarding providing default values whether or not the field is optional,
html does not have that behaviour, other form frameworks don't have it, it
is certainly unexpected for me to find out that the form framework is
providing default values for me when I don't explicitly tell it to.

I would want to user to think first before entering a value there. When
there is an initial value provided automatically, it kind of leads the user
to ignore that field because human perception kind of works like that. An
input is something you put things in, and if there already is something in
there, you automatically think you are done with it and don't even check if
you wanted to enter the correct number in there.

So a default should not be provided in any case. Just bad UX!

**Comment by serkandurusoy** [comment]
Yes, I have an optional: true field with a max value (no default, no min) and it shows the max as an initial value when form is rendered.

```
budget: {
  type: Number,
  max: 2147483647,
  optional: true,
}
```

Regarding providing default values whether or not the field is optional, html does not have that behaviour, other form frameworks don't have it, it is certainly unexpected for me to find out that the form framework is providing default values for me when I don't explicitly tell it to.

I would want to user to think first before entering a value there. When there is an initial value provided automatically, it kind of leads the user to ignore that field because human perception kind of works like that. An input is something you put things in, and if there already is something in there, you automatically think you are done with it and don't even check if you wanted to enter the correct number in there.

So a default should not be provided in any case. Just bad UX!

**Comment by todda00** [comment]
I just tried this with a field with optional: true in the schema and it is still populating with an initial value. Here are the props for an example field:

![localhost_3005_register_player_athletics](https://cloud.githubusercontent.com/assets/8363924/16653618/b14d37c4-441f-11e6-8c45-5ce3a96dd521.png)

and the corresponding schema:
```
  'height.feet':{
    type: Number,
    optional: true,
    min: 4,
    max: 8
  },
```

**Comment by todda00** [comment]
And FWIW I agree that adding a initial value based off min / max is odd behavior. Like I said previously, if the developer wishes to set a default, they can do so with the model.
