### ISSUE TITLE
Feature Request: Add a prop to add classNames to a nested field's children

### ISSUE THREAD

**Issue by todda00** [vazco/uniforms#60]
I added a field which is an array of objects, and got the wonderful nested form, but I am unable to apply a class to the child fields. If a prop was exposed to add childrenClasses, I would be able to add grid classes (or any other classes needed) to child fields. I am using the bootstrap-4 package.

https://github.com/vazco/uniforms/blob/65088ca36ea8b1680c357bc03b4214cb6faaa0cc/packages/uniforms-bootstrap4/src/components/fields/NestField.js#L34

I am looking to place the fields 2 per row, so I was looking to add .col-xs-12 .col-md-6 classes to the inner fields.

**Comment by radekmie** [comment]
That makes sense. It would be quite neat to have something like `itemProps` (or something similar), in every `ListField`.

**Comment by todda00** [comment]
Its not working as expected, here is my field:
```
<AutoField name='schoolAthletics.assistantCoaches' itemProps={{testProp: 'test', className: 'col-md-6'}} />
```

Seems as if there are 2 issues, my testProp is getting to the Nest component, but not inside of it, and the className is not even getting that far, being overwritten by col-xs-11:

![localhost_3005_register_coach_athletics](https://cloud.githubusercontent.com/assets/8363924/16746297/b4a496e0-4787-11e6-957a-094c58a03e58.png)

**Comment by radekmie** [comment]
Well: [1](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap3/src/components/fields/ListField.js#L62) and [2](https://github.com/vazco/uniforms/blob/master/packages/uniforms-bootstrap3/src/components/fields/ListItemField.js#L24). I don't really know, why there's fixed className. @zeroasterisk, could you make a comment here?

Despite of all - if you think, that it should be changed - please, make a pull request, because I don't have much experience with bootstrap.
