### ISSUE TITLE
Why is the "field level validation" feature not supported?

### ISSUE THREAD

**Issue by rootsher** [vazco/uniforms#615]

**Comment by radekmie** [comment]
Hi @rootsher. The reason is that most of the schema-based validators do not have this feature. If we'd like to implement it, we'd have to think out a way to do it for every single schema we'd like to support. It's also non-trivial in most cases, as validation of a field may depend on other fields' values, e.g. _`displayName` is not required if `name` is filled in_, or _one of `username` and `email` is required_.

As a side note, please do not file empty issues. Any context will help us to answer as well as future users to search for it.

**Comment by rootsher** [comment]
Ok, but maybe I can build custom validator / bridge and implement this logic there, yes?
Here https://uniforms.tools/docs/examples-custom-bridge#validator-definition I can implement excacly this what you write, yes?

Empty issue? without description yes? (I thought the title alone would be enough)..

**Comment by rootsher** [comment]
I thought that "field level validation" applies to the example of displaying an error directly next to the field... But this is probably about defining the field validation logic in the schema, right?

**Comment by radekmie** [comment]
You can create any kind of validator you want, but the thing is that the validator itself validates the whole model at once, not each field separately.

Displaying an error next to the field is implemented in two parts: first is that each bridge implements a `getErrorMessage(name, error)` method for getting an error message for one field and pass it as an `errorMessage` prop, second is the `showInlineError` property, which tells the field to display the provided error message (implementation may differ between themes and fields).

Yes, I meant no description. And this title is enough, but it's always easier to look it up later.

**Comment by radekmie** [comment]
I'm closing as the question seems to be already answered. Feel free to comment anyway.
