### ISSUE TITLE
Validation Errors should not rely on throw/catch

### ISSUE THREAD

**Issue by refactorized** [vazco/uniforms#644]
Validators currently work by throwing an object that is at a minimum `{ details: arrayOfErrors}`

This is not best practice as validation errors are not actually runtime errors but the proper result of a working validator against a currently invalid model.

In future versions it would be better to handle this via returning errors directly (versus returning nothing to indicate success), using promises, error first callbacks, etc.

**Side note:** 

The current system also requires throwing a somewhat nonstandard Error object that cannot be created via the Error() constructor alone.  If I am using, for instance the JSONSchemaBridge and want to throw a standard Error object (as to appease a linter) I would need the following code:

```
throw Object.assign(new Error('Validation Error'), { details: validator.errors })
```

Of course one could argue throwing a standard Error object is perhaps worse because, once again, this is not an actual error condition.  In my case I settle on just disabling ESLint for the line in question.

**Comment by radekmie** [comment]
Hi @refactorized. Thanks for actually filing this issue.

It's not true that you are forced to throw an object literal or an Error instance. You can create a custom ValidationError class for this very case (like SimpleSchema does).

In general, I agree that we should have used returned value, it would simplify a few things. Especially typing - it is impossible to type check it without some higher abstraction like checked errors or algebraic effects (none available in TypeScript at the moment).

Then why is it implemented that way? Well, the first bridge ever was the SimpleSchema (the Meteor one), and its validator throws an error instead of returning it. It was perfectly fine, up to the point when we wanted to add `onSubmitSuccess`/`onSubmitFailure` and async validation. Of course, we managed to do so, but the solution is not very elegant.

_You can read the full discussion on [Gitter](https://gitter.im/vazco/uniforms?at=5dcac85a5eb2e813db0fa005)._
