### ISSUE TITLE
Dom prop types not correctly filtered (bootstrap3)

### ISSUE THREAD

**Issue by Pagebakers** [vazco/uniforms#653]
We're using the bootstrap3 theme and are getting this error:

```
backend.js:6 Warning: Invalid value for prop `options` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details,
```

Options is a function returning the options array, using a plain object doesn't throw any errors.
We're using a function here to keep the labels reactive (we are still transitioning away from legacy autoform)

We are using SimpleSchema and AutoField

```js
new SimpleSchema({
    period: {
      type: String,
      optional: true,
      uniforms: {
        placeholder: () => __('All'),
        options() {
          return [{
            value: 'day',
            label: __('Once per day')
          }, {
            value: 'week',
            label: __('Once per week')
          }]
        }
      }
    }
```

```js
 <AutoField name="period" />
```

**Comment by Pagebakers** [comment]
Looks like options is missing from registered props in
https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/filterDOMProps.ts

**Comment by radekmie** [comment]
Hi, @Pagebakers. I'm not surprised you've noticed it while transitioning from the AutoForms - so did we back in the day. I'm not really sure if we should include it in the core, as it's not a standard SimpleSchema construct, but something that uniforms support because AutoForms did. What you can do now is to call `filterDOMProps.register` by yourself:

```ts
filterDOMProps.register('options');
```

It'll work as expected. In my projects, we do keep far more metadata directly in the schema and it's common to filter it out this way.

**Comment by Pagebakers** [comment]
Thanks, that'll work indeed!
