### ISSUE TITLE
Dirty HTML tags

### ISSUE THREAD

**Issue by metamn** [vazco/uniforms#669]
Hello,

I've just run the example from https://github.com/vazco/uniforms/issues/549 
The generated HTML contains lots of dirty tags:

```
<div class="field" items="[object Object]" options="[object Object],[object Object],[object Object]">....
```

![Screenshot from 2019-12-18 10-11-31](https://user-images.githubusercontent.com/86295/71068164-cd2b8a00-217e-11ea-92ce-8310fc913ecd.png)

Thanks :)

**Comment by radekmie** [comment]
Hi @metamn. It's because not all schema props are registered as DOM ones. If you are defining custom props, like `options` (which are understood by your schema or components) you can filter them out using [`filterDOMProps.register`](https://uniforms.tools/docs/api-helpers/#filterdompropsregisterpropa-propb-propc-). By default all components should filter all of their props passed to DOM, but if you find any that don't - let us know.
