### ISSUE TITLE
Feature request: Accordion as replacement for ListField

### ISSUE THREAD

**Issue by RSchwan** [vazco/uniforms#69]
I think the ListField component is a bit confusing. If you have a lot of items it's hard to navigate.
The advantage of an accordion is that you only see one open item at a time.
Per example for bootstrap it can be accomplished with panels. [See React-Bootstrap as example.](https://react-bootstrap.github.io/components.html#panels-accordion)
I think the user experience would be much better.
However I don't know how hard it is to implement. It is also possible to add it as an alternative to the existing ListField.

**Comment by serkandurusoy** [comment]
I must admit that I don't like the idea of an accordeon in a form for
master / detail inputs since most usecases require user to be aware of the
other items in the list at a single glance.

That being said, I agree there may be unique cases where an accordeon can
be useful, but I don't see where in the context of a forms library.

That also being said - :) - it is so easy to take the existing list
components, copy them to create your own components that reflect the markup
required to get an accordeon going in your preferred ui framework, and
import that to your form instead of the stock components.

Just take a look at how they are implemented in unstyled, bootstrap3/4 and
semanticui versions and you will immediately see a world of opportunities
open up before you :)

**Comment by radekmie** [comment]
Well, I agree with @serkandurusoy - it's easy to create such field. Certainly, I'm against adding fields, that could be used only in few packages and not in all of them - it would be hard to implement _unstyled accordion_. If you need some help with custom fields, open another issue, comment here or write me directly.
