### ISSUE TITLE
SimpleSchema: minCount arrays with options set empty checkboxes 

### ISSUE THREAD

**Issue by danyhiol** [vazco/uniforms#691]
When defining an `array` schema with `minCount` and `options`, `AutoForm` renders the field with empty `checkboxes`.
Consider the following schema:
```
members: {
    type: Array,
    minCount: 2, 
  },
  "members.$": {
    type: String,
    uniforms: {
       options: [{label: "Label1", value: "val1"}, {label: "Label2", value: "val2"}]
    }
}
```
On the playground, this will result in a `SelectField` with **2 empty checkboxes**. More over, no validation will be apply even taught no options is choosen when submitting the form. Meaning the array field is prepopulated with null values that are consider as valid from the schema.

1. The members' array should not be populated with null values when using `minCount`. It should be empty and validated.
2. The UI should not display empty checkboxes. Just like with null values, it should be empty and validated.

**Comment by kestarumper** [comment]
Hi @danyhiol,

We've patched displaying empty boxes, but still, you should include the `initialValue` parameter inside your schema because uniforms cannot infer the default value of array elements used to produce an initial state of the form because **SimpleSchema** does not support that. A quick fix to you schema would be the following
```
new SimpleSchema({
  members: {
    type: Array,
    minCount: 2,
    uniforms: {
       initialValue: []
    }
  },
  "members.$": {
    type: String,
    uniforms: {
       options: [{label: "Label1", value: "val1"}, {label: "Label2", value: "val2"}]
    }
  }
})
```

You can also check it on playground [here](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcIDqUA2BjA9gWygEIQAacCHMGZUAQwFd4cZaA3KZAM1ozjIaYt2AEUy0AnsgCMABhlkAJgEsWAIwxQFXHnxAZaqzMngR6UMmH1YoACxwYFUCNt7mQMLDah5ayEADsoAHcAAgBlJTxLKDDPb1oACmAAHX8QkII8QwgYJBCUtPSQ-HEwKDyAQQgICRJUooylfwBhHHp_eDyAJjrC9PalThwIPFz8-ob0pqV4JR4ANR4zPIBtAF0J9IBfCa3e9OSQTOyYADoAEkO8goaSsrywkyaAc32igaGRsZvJkMpZnD-MYrYD6QwYPKHAAyBkwUkOJBCrCW5RCh2RGHhID2-TBmEhIBh4K6CKRKIJGJJ2I2fRCO0K9K2AEpSO47EEAJL-DBNKAAUWqwxculoMHE_iwAHl_GF6Ko8DNhW5ReKpf5FjyFLR4BwkNxXHsQPAvAQ_LQOlotkA).

**Comment by danyhiol** [comment]
@kestarumper that's great. 
The workaround I haded was to initialize the `members` array it on the client with `[]`, because using `defaultValue: []` had no effect. I was actually thinking using `deafautlValue` would have the same effect as using `initialValue`.
Thanks for the fix.

**Comment by danyhiol** [comment]
@kestarumper sry but i'll have to disturb you again with another issue that might be related to this one.

check this schema:

```
new SimpleSchema({
  members: {
    type: Array,
    minCount: 2,
    uniforms: {
       initialValue: [],
       mode: "tags",
       allowClear: true,
       options: []
    }
  },
  "members.$": {
    type: String,
    regEx: SimpleSchema.RegEx.EmailWithTLD,
  }
})
```
[Playground](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcIDqUA2BjA9gWygEIQAacCHMGZUAQwFd4cZaA3KZeCeqMhpluwAimWgE9kARgAM0sgBMAliwBGGKPOQAzWhjhkMtFZk7de4Q1igALHBnlQIpnmRhZrUPLWQgAdlAB3AAIAZUU8MHUQ909aAApgAB1fIKCCPGMIGCQgpJTUoPgxMCgcgEEICHESZIK0xV8AYRx6X3gcgCYa_NTWxS0cCDxs3Nq61IbFeEVdADVdHhyAbQBdbvHUvBwHHMSQeFoAcxg99Y3dDBwAxvVaCByuFzHxymmcXxHV56CAXzGfs57dKZGAAOgAJHscnk6kUSjkQlwGoczqloIcAKIADwR4UiUGiHi8oIASlBMVjQRivIoMKgptYACoAGSEZz-vh-AEpSCAYLYAgBJXwYBpQDGVQbOcy0GBiXxYADyvhC9BUeCm2l0-hAsvlSt881F8lo8A4SB0eigAP2RPNuramh-QA)

The regEx (`regEx: SimpleSchema.RegEx.EmailWithTLD`) validation is not applied inline. Without the `ErrorsField`, the user won't know why the form submission button is deactivated.

**Comment by kestarumper** [comment]
Hi @danyhiol,

After the initial investigation, we've identified that's a problem with a field and how it displays its errors. Please create a separate issue for that. Thanks for pointing that out.
