### ISSUE TITLE
uniforms community

### ISSUE THREAD

**Issue by kingsleyzissou** [vazco/uniforms#705]
I've been working with @wtrocki on a library for Ionic. What do you think about a uniforms community organisation for the community to contribute?

Also thanks for the alpha release!

**Comment by wtrocki** [comment]
To add organization is just to aggregate the extensions to various UI frameworks that core team do not maintain. This is to popularize Uniforms thru wider adoption of the UX frameworks. For example our team is very strongly attached to Ionic and we will be maintaining Ionic extension in the community org. 

It is nice to have org as we want to invite uniforms team to manage it etc. 
The alternative will be to list some community extension of the website

**Comment by radekmie** [comment]
Hi @kingsleyzissou, @wtrocki. I'm really surprised to see such a question. We thought about creating an organization in the past, but it seems not to give much value. If you see something I don't - share it here.

Currently, all uniforms packages are contained within only one (mono) repository. This means all issues are in one place. It does make sense, as most of the time reporters are not sure, where the problem is - in the core or in a theme. It also simplifies updates and releases as it's always one changelog, one repository, one tooling, one version, etc.

> [...] to aggregate the extensions to various UI frameworks that core team do not maintain.

Right now, we have six themes, three of them were built by the community (AntD, Bootstrap 3, and Bootstrap 4). I'm aware that there are different ones, maintained (or already orphaned) by someone else. We are open to add more packages, but it means we are expected to maintain them (and we do), therefore we're not accepting everything straight away.

If you are building a new, Ionic theme - just do it. If - one day - you'd like it to become an "official one" (it's a terrible name; I meant adding it to this repository), then we can discuss that. It's also possible to add external collaborators to this repository as well.

Adding a list of community-maintained packages is definitely possible. We'd just need to decide where and how it should be presented.

**Comment by radekmie** [comment]
I understand everything is clear. If you have any doubts - feel free to comment.
