### ISSUE TITLE
DateField Props for separating Date and Time is not supported ? 

### ISSUE THREAD

**Issue by mahi-vlinder** [vazco/uniforms#724]
DateField Props for separating Date and Time is not supported ?

**Comment by kestarumper** [comment]
Hi @mahi-vlinder,
It's not supported by uniforms because not **all** themes support that. On the other hand, you can freely create your custom component. For example, you could start with [`<DateField />`](https://uniforms.tools/docs/api-fields/#datefield) and use it to create `<DateTimeField />` for your custom theme.

Feels free to ask more questions if any arise.

**Comment by kestarumper** [comment]
I'm closing this issue since no reply was given. Feel free to re-open.
