### ISSUE TITLE
[Discussion] Debounce on a live document update with autosave

### ISSUE THREAD

**Issue by serkandurusoy** [vazco/uniforms#73]
Continuing the discussion on from [#29](https://github.com/vazco/uniforms/issues/29#issuecomment-232172308) 

cc: @guciek27

@radekmie I would love to hear your comments on this one!

**Comment by radekmie** [comment]
**Story**
We've also encountered a problem with _live document_ - a form which is a real-time view of a document from database. There are two problems -  concurrent edition and database latency. We couldn't do much about that second one, but we've found a solution to the first one.

**Solution? [`DualLink`](https://github.com/vazco/meteor-universe-utilities-react#duallinkmixin)**
Basically, it works like this - you've got two states - remote and local. Remote state is your _live document_ (eg. `Collection.findOne(_id)` in Meteor), local state is user input. Full state is remote state patched with local state (`{...remote, ...local}`).

**Example**
There's a document with 2 fields - `title`, `subtitle` and an autorun, that's refreshing our doc from database setting it as remote state. If user does nothing - just looking at the form - every change in database is updated in the form, but when user change any field - it's added to the local state and _frozen_ for user - change in database won't update form.

**Note**
Currently, `DualLink` is implemented as a mixin.

_I'll tag @MacRusher here, because he is the inventor of the `DualLink`. [Source](https://github.com/vazco/meteor-universe-utilities-react/blob/master/mixins/dualLink.js)._

**Comment by serkandurusoy** [comment]
@radekmie @MacRusher quite an efficient implementation, indeed. Luckily I'm concerned with up-to-date information on individual form fields and last-write-wins is more favorable, also concurrent writes is less of a concern due to use cases at hand.

But yeah, this is indeed a very valid concern and this would be basically what I would have implemented, but perhaps I would have used redux as an intermediary store.

BTW, are you planning to refactor those mixins into HOC's?

**Comment by radekmie** [comment]
Well, we are not planning it, but if there is such need, I will consider it.

**Comment by serkandurusoy** [comment]
I was just curious about it since react world is moving away from mixins in general.

**Comment by radekmie** [comment]
We know it, but we are now using `react-komposer` instead of our `AutorunMixin` and `SubscriptionMixin`.

**Comment by serkandurusoy** [comment]
Right, I was actually just referring to dualLink :)



On Wed, Jul 20, 2016 at 11:13 PM, Radosław Miernik <notifications@github.com

**Comment by radekmie** [comment]
I'll think about it.
