### ISSUE TITLE
JSON Schema - 'allOf' nested within the 'array' type field breaks the form

### ISSUE THREAD

**Issue by Mhal007** [vazco/uniforms#746]
When `allOf` is nested within the `array` type property, the form no longer works correctly. I'm not able to add new nested fields using the `+` button - they are not appearing.

**Schema that I've used:**
```
const schema = {
    title: 'Form',
    type: 'object',
    properties: {
      parentField: {
        items: {
          type: 'object',
          properties: {
            childField: {
              type: 'string',
            },
          },
          allOf: [{ required: ['childField'] }],
        },
        type: 'array',
      },
    },
  };
```

**Result:**
![image](https://user-images.githubusercontent.com/16467173/84750071-1daf6300-afbb-11ea-989d-de68b6eeabf9.png)

**Comment by radekmie** [comment]
Hi @Mhal007. It looks like the problem is in the merging part ([v2](https://github.com/vazco/uniforms/blob/fd390972525686703b7f27e922b0f4178901d6ee/packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts#L197), [v3](https://github.com/vazco/uniforms/blob/dad1df628b35f23b0d4cd53695d003e932b0d61f/packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts#L187-L188)). Probably changing `{}` to `_definition.properties ?? {}` and `[]` to `_definition.required` will do the job. Could you check it locally?

**Comment by Mhal007** [comment]
Unfortunately, it ain't it. Still, the same issue occurs.
