### ISSUE TITLE
Cutom beforeSubmit for every field

### ISSUE THREAD

**Issue by mariusrak** [vazco/uniforms#789]
Hi, would it be possible to add a feature for custom beforeSave for every field? Currently, it is possible to define custom component by `.uniforms.component` property of a field. Similarly there could be `.uniforms.beforeSubmit` property which would have a function receiving a current value as a parameter (and possibly a model as second) and returning a value that should be submitted. This is currently achievable by common beforeSubmit, but it might be useful also per-field. It would provide more clarity on a code.
Thanks.

**Comment by Floriferous** [comment]
Why don't you customize your own `onSubmit` handler?

Something like this:

```js
const CustomAutoForm = ({ onSubmit, onBeforeSubmit }) => {
  const enhancedOnSubmit = formValues => {
    if (onBeforeSubmit) {
      onBeforeSubmit(formValues);
    }

    return onSubmit(formValues);
  };

  return <AutoForm onSubmit={enhancedOnSubmit} />
}

// And then
<CustomAutoForm onSubmit={(formValues) => storeData(formValues)} onBeforeSubmit={formValues => doSomething(formValues)} />
```

Or you could write a slightly more advanced version where you can pass a `onBeforeSubmitMap` that is a map of functions that each receives the value of a specific field?

**Comment by radekmie** [comment]
Hi @mariusrak and thanks @Floriferous for your example. I assume that's exactly what @mariusrak called "common `beforeSubmit`". While this feature is interesting, it raises a few non-trivial questions like _what if a field is submitted but not rendered?_ or _how it translates to other schemas with conditional fields?_. Because of that, we've decided not to implement it.

It's possible to do something similar by yourself, using the "common `beforeSubmit`". In short, walk the schema in `onSubmit` and call all helpers you need, based on the model (or not). It gives you more possibilities and separates the concern of schema (shape, validation) and form (data submission).
