### ISSUE TITLE
Validation fails after first submit when using state value for the field value

### ISSUE THREAD

**Issue by tomtom87** [vazco/uniforms#790]
I'm setting a `<NumField id='position' name='position' label="Price" decimal={true} value={this.state.myValue} />`

The state value gets updated inside the submit function. When I try and submit the form again, the field gives a validation error that it's not set. If I make the field optional - the value is undefined. Although in the browser I can see the value is set and check in inspect element and it is being set.

I am calling reset() after submit, as otherwise all the hidden fields are also unset. How can I work around this so it works correctly and revalidates? If I click on the input and try again, it will clear the validation error and function. 

I am only having this issue if I try to resubmit the form after submission without clicking anything other than submit. If I click any field it will reset the validator and work. Please advise

**Comment by kestarumper** [comment]
Hello @tomtom87 ,
In general, you shouldn't be handling `value` on a `Field` by yourself when using uniforms, because that value won't be reflected in the uniforms model.

> Although in the browser I can see the value is set and check in inspect element and it is being set.  

This is normal behavior, because `value` is just being passed to the component, but not to the model.

If you need to access this value somewhere else, you can find it in uniforms form model.

I hope this helps, feel free to ask more questions.

**Comment by tomtom87** [comment]
Thanks, I’ve used a hidden field instead and it works beautifully now.

**Comment by kestarumper** [comment]
I'm closing this issue because it was resolved.

**Comment by tomtom87** [comment]
thanks man
