### ISSUE TITLE
Regression with html5 inputs

### ISSUE THREAD

**Issue by serkandurusoy** [vazco/uniforms#80]
Here's the output on the console while I'm typing in some text into a text field which has type="email" prop on it.

![image](https://cloud.githubusercontent.com/assets/4649948/17000517/95a39e76-4ecb-11e6-84f0-5776a655f5be.png)

We had a similar problem before which we discussed [over at issue #22](https://github.com/vazco/uniforms/issues/22)

**Comment by radekmie** [comment]
So I'll investigate it one more time.

**Comment by radekmie** [comment]
I've spend some time to track this down and this turned out to be a React regression. Here are my results:

```
0.14.8         OK
15.0.0-rc.2    OK
15.0.0         3x
15.0.1         OK
15.0.2-alpha.1 OK
15.0.2-alpha.2 OK
15.0.2-alpha.3 OK
15.0.2-alpha.4 OK
15.0.2         OK
15.0.3-alpha.1 OK
15.0.3-alpha.2 OK
15.1.0-alpha.1 OK
15.1.0         OK
15.2.0-rc.1    1x
15.2.0-rc.2    1x
15.2.0         1x
15.2.1         1x
15.3.0-rc.1    1x
15.3.0-rc.2    1x
15.3.0-rc.3    1x
```

_(`1x` - one warning, `3x` - three warnings, `OK` - no warnings)_

It's clearly a regression in `15.2.0-rc.1`, so I've tried to see a diff between `15.1.0` and `15.2.0-rc.1`. Then I learned, that React is not tagging their release candidates, so I've tried to diff `15.1.0` with `15.2.0`. [Well, it's something](https://github.com/facebook/react/compare/v15.1.0...v15.2.0) _(it may freeze your browser)_. I don't really know, what to do now.

**Comment by serkandurusoy** [comment]
Wow, nice work!

And I think these two are somewhat relevant to our case, the latter probably solving our case inadvertantly

https://github.com/facebook/react/issues/6441
https://github.com/facebook/react/pull/7333

**Comment by radekmie** [comment]
Yes, kind of - I've even referred to them in my issue facebook/react#6992. Hope it will help (and get merged asap).

I'll close it for now, as it's not uniforms issue.

**Comment by radekmie** [comment]
I've added a note in README about it.
