### ISSUE TITLE
Asyc call to onChange

### ISSUE THREAD

**Issue by cesarve77** [vazco/uniforms#804]
First sorry for my english:

I'm creating my custom FileField which upload files to aws and call onChange when is done, but it is no working due to when onChange is called asyc do not update the value prop.
```
const FileUpload=({onChange,value})=>{
        console.log('print actual value', value)
        return <Uploader value={value} onNewFile=(file)=>{
                uploadFile(file).then(serverFile=>onChange(serverFile))
        }} />
}
```
In the previous examplem when onChange is called the custom field does not receive the new value, "print actual value" is not called any amor after the first render.

I made is small repo to reproduce the bug

https://github.com/cesarve77/uniform-bug

this does work:
```
    const _onChange=(event)=>{
        event.persist()
        onChange(event.target.value)
    }
```
this does not work:
```
    const _onChange=(event)=>{
        event.persist()
        setTimeout(()=>onChange(event.target.value),0)
    }
```

**Comment by radekmie** [comment]
Hi @cesarve77. I've tried your reproduction and the problem lays in the usage of `event`. Even with `event.persist()`, `event.target` state won't be preserved, and after the timeout, `event.target.value` will be the actual DOM value. An example fix looks like this:

```diff
- event.persist();
- setTimeout(() => onChange(event.target.value), 1000);
+ const { value } = event.target;
+ setTimeout(() => onChange(value), 1000);
```

But regarding the asynchronous (in Promise chain) call - it doesn't change anything. Technically speaking, every call to `onChange` is asynchronous in a way. Waiting for user input is the same as waiting for user input and for a timeout or a Promise. The below code works:

```tsx
async function _onChange(event) {
  const { value } = event.target;
  await new Promise(resolve => setTimeout(resolve, 1000));
  onChange(value);
}
```

Just keep in mind, that such a delay of HTML inputs will result in incorrect behavior, as the DOM value changes less often than it should. It shouldn't influence your `FileUpload` in any way. Could you check if the problem was similar?

**Comment by cesarve77** [comment]
Thanks for  your quick response.

I see.

In my upload component it still not working, I will try to figure it out what is happening.

thanks

**Comment by radekmie** [comment]
I hope everything works now. If not, feel free to comment here or file a new issue.
