### ISSUE TITLE
Errors during onSubmit swalloved

### ISSUE THREAD

**Issue by mariusrak** [vazco/uniforms#812]
If there is an error during onSubmit function execution. It is not accesible. It simply does nothing. No error, no info, no throw. Only way to access it is by using debugger's "Pause on exceptions".

**Comment by radekmie** [comment]
Hi @mariusrak. All possible errors (schema validator, `onValidate`, `onSubmit`) are stored in `state.error` and used in the same way (also accessible in `context.error`). That means, if you want to see this error, you have to use `ErrorsField` (it'll show all errors) or match your schema error format (that will show the error under a given field).

And yes, the error is suppressed, as if it's handled by the form, there's no point in logging it to the console.

**Comment by mariusrak** [comment]
If I throw an error in `onSubmit` it is not accessible anywhere. The only component with state or prop field `error` is `AutoValidatedQuickForm`. It has `props.error` and `state.error` bot `null`.

I've logged the error before throwing it and it is there, it is just not accessible.

**Comment by mariusrak** [comment]
Also, if I set `ErrorsField` (respectively `ErrorField`) I get an error:
```React does not recognize the `ErrorsField` prop on a DOM element```

**Comment by mariusrak** [comment]
So after few unsuccessful attempts I've understood how things works. Maybe it would be possible to describe error handling in documentation more concise.

**Comment by mariusrak** [comment]
How can I access an error received from server during onSubmit execution? I need to act on it in AutoForm, e.g. show the received error as an validation error.

**Comment by radekmie** [comment]
@mariusrak You simply don't. If you want the server error to appear in the form, transform it according to your schema format in the `onSubmit` and return/reject it. The reason why you see `error: null` is probably the error format. For example, for SimpleSchema it should look like a `ValidationError`, so an object with `details: [{ name: string }]` property. It's handled in [`getError`](https://github.com/vazco/uniforms/blob/ab34011a489c9b29325f486f24bd0007bc62d9a6/packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts#L17-L20) then.

**Comment by mariusrak** [comment]
So I've tried to 
```
throw { details: [{ name: e.message || e }] };
```
and it is still not in `error` field.

**Comment by radekmie** [comment]
If you are using v3 return it instead of throwing. What is more, the `name` have to match schema field if you’d like to show this error next to a field.

**Comment by mariusrak** [comment]
```
        return Object.assign(new Error(), {
                details: [{ [Object.keys(model)[0]]: e.message || e }],
        });
```
Didn't help also. But anyways, this seem like not a good API. There could be more straightforward way.

**Comment by radekmie** [comment]
OK, I finally understand what the problem here is. So, back in #711 I wanted to unify the way of error handling between validation on submission. While I _mostly_ succeed, there's one problem: **synchronous** errors from `onSubmit` are [not handled incorrectly](https://github.com/vazco/uniforms/blob/1057654d1722c21aacc7a38eadf82946fbefbcab/packages/uniforms/src/BaseForm.tsx#L242-L245).

So, to sum up, also answering your questions regarding the API for that:
* If you want to show errors in the form, the bridge handles all of that. Every error has to be handled there - the one from the `error` prop, validation, `onValidate`, and `onSubmit`.
* That means there's no need to provide a custom API for that. If you'll stick to the error shape of your bridge, it _just works_. For example, using `ajv` with JSON Schema allows you to have additional validations on the server using the same library (e.g. using custom keywords). Another approach would be to create a custom bridge, deriving the one you use now, to understand other types of errors.
* As I said before, for SimpleSchema, the error has to match the `ValidationError` shape. A correct example would look like this: `{ details: [{ name: 'fieldName', type: 'error type' }] }`, where `'error type'` [has to be already registered](https://github.com/aldeed/simpl-schema/tree/50128841fa7fc2d137c36a397054279144caea3d#custom-field-validation). You can read more in SimpleSchema documentation.
* Having said that, I found out that there's a problem and if you return the error from `onSubmit` it won't work (it should), but returning `Promise.reject(error)` will (as expected). I'll report this error separately.

**Comment by mariusrak** [comment]
I've made my `onSubmit` `async` and this now works:
```javascript
throw {
        details: [
                {
                        name: Object.keys(model)[0],
                        type: e.message || e,
                },
        ],
};
```
