### ISSUE TITLE
Bootstrap 4 - no icon for add nested item

### ISSUE THREAD

**Issue by mikkelking** [vazco/uniforms#820]
This started out by trying to create an array of items with its own structure. The autoform displays nicely with one problem, that the "+" icon is not visible.

It looks like the markup is `<i class="octicon plus"/>` so I tried importing `octicon-react` but that didn't help.

The next idea was to use the `<ListAddField>` , using `import { ListAddField } from 'uniforms-unstyled'`

Putting it on the form, I get  the error`Invariant Violation: useForm must be used within a form.`

I tried putting it inside a LIstField, but nothing seems to work, I am probably doing something silly

```
      <AutoForm schema={schema} onSubmit={console.log} model={data}>
        <ListField name="buyers">
        <ListAddField addIcon={<PlusIcon />} />{' '}
          <ListItemField name="$">
            {' '}
            <NestField name="">
              {' '}
              <TextField name="fullname" />
              <TextField name="email" />
              <TextField name="mobile" />
            </NestField>
          </ListItemField>
        </ListField>
        <AutoFields />
        <ErrorsField></ErrorsField>
        <SubmitField />
      </AutoForm>
```

There is a repo at https://github.com/Back2bikes/my-uniforms-sample if you want to have a look. Click on the _custom_ link

**Comment by mikkelking** [comment]
It looks like I was approaching it the wrong way...

I was going too deep. Even though things like `<ListAddFIeld>` are exposed, it doesn't work as expected. The "fix" was a whole lot simpler: 

```html
      <ListField
          name="buyers"
          addIcon={<PlusIcon />}
          removeIcon={<TrashcanIcon />}
        ></ListField>
```
That works fine, so perhaps this issue can be closed. 
I would like, however, to be able to change the add button to be something much more obvious like a button saying "Add another person". An ability to supply a component would be useful - as per #640

**Comment by radekmie** [comment]
Hi @mikkelking. Sorry for the delay, but we somehow overlooked this one. While I see you've already managed to work that out, I'd like to give some more detailed explanation as it may be a little counterintuitive.

_(it may be a little bit too broad but we may use it later for the docs)_

First of all, let's start with the way how `ListField` components are structured. The main one, [`ListField`, renders **one** `ListAddField` **directly**](https://github.com/vazco/uniforms/blob/33c767c343aaa51474891454aa9bcb3986ef1c47/packages/uniforms-bootstrap4/src/ListField.tsx#L48-L52), and [clones its children for each element of its `value`](https://github.com/vazco/uniforms/blob/33c767c343aaa51474891454aa9bcb3986ef1c47/packages/uniforms-bootstrap4/src/ListField.tsx#L60-L71) (hence the _list_ in the name). Note that it's `name` prop is `$`, which means it's going to be a _list element_, not the _list itself_. Then, most commonly ([including `ListField` defaults](https://github.com/vazco/uniforms/blob/33c767c343aaa51474891454aa9bcb3986ef1c47/packages/uniforms-bootstrap4/src/ListField.tsx#L26)), `ListItemField` is being used as the child component. That's because every list item should be removable and we wouldn't like for each field to know that it may be removable. That's why [`ListItemField` renders `ListDelField`](https://github.com/vazco/uniforms/blob/33c767c343aaa51474891454aa9bcb3986ef1c47/packages/uniforms-bootstrap4/src/ListItemField.tsx#L22) (`name` prop of `""` means _the same field as me_; a child in the JSX tree but a sibling for uniforms) **and** [own children](https://github.com/vazco/uniforms/blob/33c767c343aaa51474891454aa9bcb3986ef1c47/packages/uniforms-bootstrap4/src/ListItemField.tsx#L24) ([`AutoField` by default](https://github.com/vazco/uniforms/blob/33c767c343aaa51474891454aa9bcb3986ef1c47/packages/uniforms-bootstrap4/src/ListItemField.tsx#L15)).

Now, let's get to your code. Your first post renders `buyers` twice - once directly, using `ListField` and all of its contents (let's call this one _fully explicit_), once indirectly, using `AutoFields` (_implicit_). Then, in the second post, semi-directly, using `ListField` but without specifying `children` (_semi explicit_). Let's see how it renders **without Octicons**:
<details>

![length-0](https://user-images.githubusercontent.com/1379064/99876832-de381300-2bf9-11eb-9492-60ccaf9f5708.png)

</details>

As we can see, only one custom `PlusIcon` (`~plus~` in the screen) is being visible. To be precise, two more Octicons are present here - one in the _fully explicit_ and one in the _implicit_ form. It's because the `ListField` **always** renders `ListAddField` on its own. Now, let's see how it looks like with one element in the `buyers` array:
<details>

![length-1](https://user-images.githubusercontent.com/1379064/99876874-33742480-2bfa-11eb-9e12-1aa612d1d77f.png)

</details>

Now we see `PlusIcon` twice. The first occurrence is there because _fully explicit_ part renders it **for each of its value elements**. Also, the _Buers_ label appears twice as well, but only in the _fully explicit_ example. That's because [`ListItemField` sets its children `label` to `null` by default](https://github.com/vazco/uniforms/blob/33c767c343aaa51474891454aa9bcb3986ef1c47/packages/uniforms-bootstrap4/src/ListItemField.tsx#L15). That means, if we'll add more values, we'll see more `PlusIcon`s and labels:
<details>

![length-2](https://user-images.githubusercontent.com/1379064/99876920-7635fc80-2bfa-11eb-874e-ff431aac4b17.png)

</details>

Let's sum up:
* `ListAddField` can be set on `ListField` using props.
* `ListAddField` can be rendered elsewhere, but then it may be rendered multiple times.
* `ListDelField` is rendered by `ListItemField`, which is the default for `ListField`.

All of the code is available in [this](https://codesandbox.io/s/little-wood-qgvkx) CodeSandbox.
