### ISSUE TITLE
Broken adding of complex objects to lists

### ISSUE THREAD

**Issue by dmitry-sher** [vazco/uniforms#831]
Reproduction sandbox: https://codesandbox.io/s/youthful-shaw-g8n4k?file=/App.tsx
Demo Meteor Project: https://github.com/dmitry-sher/uniforms-bug

I'm having a schema with list of complex objects, each having `documents` field -- Array of String file ids. When we add new document to list of documents, it should be unpopulated. But somehow `documents` field for newly created object contains one undefined value. Then on Submit click it passes validation. 

Expected behaviour: `documents` field is empty Array and form doesn't passes validation.

**Comment by dmitry-sher** [comment]
i have tracked source of this to some chain of `onChange` events firing back and forth between parent and clidren classes. that i don't understand. i've found an exact place where undefined value is coming from: https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/useField.tsx#L90

```
if (options?.initialValue !== false) {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useEffect(() => {
      const required = props.required ?? schemaProps.required;
      if (required && initialValue !== undefined) {
        onChange(initialValue);
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);
  }
```

i don't know why initialValue is `[undefined]`.

maybe it's some misunderstandment on my side of minCount.
in our user story minCount means minimum number of items for form to be valid.
we are not over-restrictive and we give possibility for user to go below that threshold. maybe he needs to remove some list items before put new ones in. it's his freedom. and in current realisation, if there is minCount, i cannot go lower that value. for us it is too restrictive.. how should we use your library properly to achieve effects we want: unpopulated new objects and freedom of going temporary into invalid states?

**Comment by dmitry-sher** [comment]
if i remove minCount from `documents` field in schema, it works as expected, but now i should create my custom validator for each `documents` field in all our schemas..

**Comment by dmitry-sher** [comment]
anyway. I have `documents.$` set to String. how `undefined` is passing validation? i don't know what is actual bug here for you, but something is definitely wrong here.

**Comment by dmitry-sher** [comment]
@radekmie this is not some f...cking question, this is bug that stalled a big project and we are thinking about opting out of your library because of numerous bugs and changed conceptions in v3.

i've been trying to understand and fix this for two weeks already and you call this a `question`, wtf!!

**Comment by radekmie** [comment]
Hi @dmitry-sher. I wanted to take some time to read through your comments and reproduction, but as your comments are quite... Urging, let me reply briefly. I'm always marking issues as _question_ at first, as long as I'm not sure, whether it is an actual bug. There are other people using this library, and there's no need for marking all potential problems as bugs straight away. As always, we can change the label, no worry.

Now, please let me read through it and reply in a few minutes, OK?

**Comment by radekmie** [comment]
OK, so there are a few things here:
1. SimpleSchema has a problem with such a definition. Let's take an example:
    ```ts
    const schema = new SimpleSchema({ x: { type: Array, minCount: 1 }, 'x.$': String });
    schema.validate({ x: [] })          // Error
    schema.validate({ x: [''] })        // OK
    schema.validate({ x: [null] })      // OK
    schema.validate({ x: [undefined] }) // OK
    ```
2. Currently, and for a long time now, uniforms treated `minCount` and `maxCount` as hard limits, also in the UI layer. This is valid, though opinionated view - I see your point here, and agree that this could be an option.
3. The `null` gets there, as while calculating the initial value of an array, we do need the initial value of its element ([source](https://github.com/vazco/uniforms/blob/27681eb8621469b6ecd15d11ca7acbfee665feab/packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts#L76-L91); @dmitry-sher also linked that). It seems, that adding `defaultValue` to the `x.$` would be enough, right? Nope: _An array item field (one that ends with ".$") cannot have defaultValue_.

Now, let's think about how to proceed here:
1. I'd say it's a bug in SimpleSchema, feels related to https://github.com/aldeed/simpl-schema/issues/321.
2. Instead of `max` [here](https://github.com/vazco/uniforms/blob/27681eb8621469b6ecd15d11ca7acbfee665feab/packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts#L81), we could say that `props.initialCount` takes precedence over `field.minCount`. However, this won't allow removing the first `minCount` elements after they were added. It is an option, preferably behind a prop.
3. (1) It'd be nice to be able to set `initialValue` for `.$` fields as well, probably using `uniforms` sub-key. (2) I think that if an array has `defaultValue` set, it should be used instead of creating a new one.

And for both, 2 and 3, separate feature requests would be the best here. Just a small write up and link to this issue is enough.

As all of these actions will take time, here's a workaround:
```tsx
// Now
export const bridge = new SimpleSchema2Bridge(schema2);

// Workaround
function makeSimpleSchema2Bridge(schema) {
  const bridge = new SimpleSchema2Bridge(schema);

  // Workaround for vazco/uniforms#831.
  bridge.getInitialValue = function (name, props) {
    const initialValue = SimpleSchema2Bridge.prototype.getInitialValue.call(this, name, props);
    if (initialValue !== undefined) return initialValue;

    switch (this.getType(name)) {
      case String:
        return '';
      default:
        return undefined;
    }
  };

  return bridge;
}

export const bridge = makeSimpleSchema2Bridge(schema2);
```

---

@dmitry-sher I understand, that you've spent time on this and had no clear answer. I'm not aware that it took you two weeks, as the issue was reported yesterday. Also, I'm a bit surprised with your comment regarding v3 changes - could you comment on it further? It's still an RC version. And for the future - please, do let us know about it, either here, on GitHub, or even via email.

**Comment by radekmie** [comment]
I think it's all clear now. Again, if you'd need any of these two issues - please do file a separate feature request. And if there are any questions about this topic, just put them here.
