### ISSUE TITLE
Generate UI automatically from schemas with If/Then clauses

### ISSUE THREAD

**Issue by afmfe-iul** [vazco/uniforms#845]
Hey there!
I've read a few issues about conditional rendering and all of them seem to point to `DisplayIf` examples.
However using that solution wouldn't be ideal because if I fail to match perfectly the schema conditions on the `DisplayIf` I will have problems.
I've got a schema similar to the one below:
![image](https://user-images.githubusercontent.com/10389190/103933239-f36df000-511a-11eb-960e-b3c39a3259a8.png)

And `fieldB` never renders. I'm wondering if I'm using if/then clauses wrongly or if there's no support to render fields conditionally out of the box?

PS- thanks a lot for `uniforms`!

**Comment by radekmie** [comment]
Hi @afmfe-iul. This example is not supported now and is planned to be supported anytime soon. The reason is that this schema depends on the current form values, and in uniforms, the schema is considered to be constant (i.e., value-independent).

Now, let's talk about the possibilities here. One would be to implement these conditions manually, using `DisplayIf` and replicating this logic within the form code. Another, requiring more custom code but also more generic, would be to create a smarter `DisplayIf`-like component, that would understand your schema. While it may be hard with `if`/`then`/`else` (uniforms don't understand these), it may be easier with making these field optional and defining their visibility withing schema (e.g. `fieldB: { type: 'string', displayIf: {equal: [{value: 'fieldA'}, 'uniforms']}` and a simple evaluator).

Also, @kestarumper may suggest something as well.

**Comment by afmfe-iul** [comment]
Hey there @radekmie, thanks for explaining our possibilities. For now we will go with the first solution you purpose.

Do you have any roadmap/date for the release of this new feature?

**Comment by radekmie** [comment]
Ah, I meant _it is not planned to be supported_! Sorry, my fault!

**Comment by radekmie** [comment]
I think it's all clear now. I'm closing, but feel free to comment anyway.

**Comment by kestarumper** [comment]
Hi @afmfe-iul,
in our project, we use schema `if/then/else` clauses for **validating** the final `Form` output, however for conditionally displaying fields we use the `DisplayIf` approach that @radekmie suggested.

Also sorry for the late response. I believe it's better than never :D
