### ISSUE TITLE
Idea: Internal immutability?

### ISSUE THREAD

**Issue by radekmie** [vazco/uniforms#86]
As I worked on optimizations recently, I thought about rewrite everything to [`immutable`](https://github.com/facebook/immutable-js/) (or something similar). It would simplify few _hard-to-keep-immutability_ places (like [this](https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/components/fields/ListDelField.js#L17-L20)) and get rid of [lodash](https://github.com/lodash/lodash) dependencies (at the moment, [5 of them](https://github.com/vazco/uniforms/blob/master/packages/uniforms/package.json#L99-L103)) in favour of this one. The main point, is the performance - [current `shouldComponentUpdate` is not that simple](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/fields/BaseField.js#L42-L94).

What do you guys think?

---

EDIT: This also seems to be a great library: [`seamless-immutable`](https://github.com/rtfeldman/seamless-immutable).

**Comment by serkandurusoy** [comment]
what about mobx? it seems very efficient!

Sent from my iPhone



On Jul 29, 2016, at 22:39, "Radosław Miernik" <notifications@github.com>
wrote:

As I worked on optimizations recently, I thought about rewrite everything
to immutable <https://github.com/facebook/immutable-js/> (or something
similar). It would simplify few *hard-to-keep-immutability* places (like
this
<https://github.com/vazco/uniforms/blob/master/packages/uniforms-unstyled/src/components/fields/ListDelField.js#L17-L20>)
and get rid of lodash <https://github.com/lodash/lodash> dependencies (at
the moment, 5 of them
<https://github.com/vazco/uniforms/blob/master/packages/uniforms/package.json#L99-L103>)
in favour of this one. The main point, is the performance - current
shouldComponentUpdate is not that simple
<https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/fields/BaseField.js#L42-L94>
.

What do you guys think?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vazco/uniforms/issues/86>, or mute the thread

**Comment by radekmie** [comment]
I'm not sure - I haven't played with mobx that much - but I think it would require a complete rewrite - current flow seems to be not compatible with _mobx way_ (again, it's just my opinion - correct me, if I'm wrong).

**Comment by serkandurusoy** [comment]
I'm not experienced with it either, but I'm currently evaluating it as an
evolution to redux stores and I think it makes sense in the way that it is
reactive and meteor is reactive and that it can be a very good bridge
as reactive  intercomponent comunication.

It aiso claims to be extremely efficient with figuring out updates to its
internal state and it utilizes shouldComponentUpdate very effectively.

And the code also becomes so much simpler.

But as I said, I'm currently just evaluating it.

**Comment by serkandurusoy** [comment]
Also take a look at this interesting article:

https://blog.risingstack.com/handling-react-forms-with-mobx-observables/

**Comment by radekmie** [comment]
I've read it some time ago. OK, so right now, I'll leave it as is - I **really** want to release `v1.0.0` (I have to focus - I'm doing too much sidework).

Maybe in the future? :question:

**Comment by serkandurusoy** [comment]
That's definitely fair! :)

**Comment by macrozone** [comment]
Performance last ;-)

I think 1.0.0 is soon ready. I'll try to do a blogpost in the next weeks about it. Maybe we should also advertise it a bit (more) on the meteor-forum! Having AutoForm on react might help some people switch from blaze to react ;-)

**Comment by radekmie** [comment]
@macrozone - you got it. I'm planning 1.0.0 in this very week. Right now I want to give it few more days, so if any bug will come out - it could be fixed before that main release.

**Comment by macrozone** [comment]
cool, using it in two projects heavily right know, will report any bug ;-)
