### ISSUE TITLE
Question: how to append custom errors to the default onValidate callback?

### ISSUE THREAD

**Issue by afmfe-iul** [vazco/uniforms#869]
Hey again!
I'm using typescript+uniforms-semantic and I'm trying to add business logic errors on top of the json schema errors when the form is validated. Currently the sample code below allows me to achieve this but I'm not very confident about the approach, I'm using `any` in some places and I'm not sure of the expected data structures.

```ts
const appendCustomError = (res: any, cond: boolean, dataPath: string, message: string): any =>
    cond ? { ...res, details: [...(res?.details || []), { dataPath, message }] } : res;

// I pass this function to my AutoForm onValidate attribute.
const onValidate = (model: MyModel) => {
  let res = bridge.validator(model);

  res = appendCustomError(
    res,
    model.fieldA > model.fieldB,
    ".fieldB",
    "fieldB must be higher than fieldA"
  );

  // Append other custom errors...

  return res;
};
```

Any guidance on how to better achieve this would be very appreciated!

**Comment by radekmie** [comment]
Hi @afmfe-iul. First of all, you shouldn't call `bridge.validator` manually - the `onValidate` receives a second argument which is the actual `error` ([source](https://github.com/vazco/uniforms/blob/ec5030886f0af285657583e58654b29ef280c153/packages/uniforms/src/ValidatedForm.tsx#L162)). Now, [the `error` argument is of type `any`](https://github.com/vazco/uniforms/blob/ec5030886f0af285657583e58654b29ef280c153/packages/uniforms/src/ValidatedForm.tsx#L13), because the form does not know, what the error type is gonna be. But if you are using ajv, you can securely assume, that it is going to be an ajv error. Luckily, starting in version 7, ajv is 100% TypeScript, and you could use the [`ErrorObject` type](https://github.com/ajv-validator/ajv/blob/33722772d89b428ff167730cd7955adff3cc8a0d/lib/types/index.ts#L76-L89):

```tsx
function onValidate(model: MyModel, error: null | { details: ErrorObject[] }) { /* ... */ }
```

_(I haven't tested it)_

**Comment by afmfe-iul** [comment]
Works like a charm since we are using ajv 7, thanks again @radekmie
