### ISSUE TITLE
Semantic dropdown list cropped in Firefox 

### ISSUE THREAD

**Issue by slavb18** [vazco/uniforms#873]
Semantic dropdown list text cropped  in Firefox (bottom line) 
Quick fix:
```css
.ui.selection.dropdown { 
  padding-top: 0.5em !important;
  padding-bottom: 0.5em !important;
}
```

Example schema

```javascript
(() => {
  const ajv = new Ajv({ allErrors: true, useDefaults: true });
  const schema = {
    title: 'Address',
    type: 'object',
    properties: {
      city: { type: 'string' },
      state: { type: 'string' },
      street: { type: 'string',      "enum": ["Street", "Avenue", "Boulevard"] },
      zip: { type: 'string', pattern: '[0-9]{5}' },
    },
    required: ['street', 'zip', 'state'],
  };

  function createValidator(schema) {
    const validator = ajv.compile(schema);

    return (model) => {
      validator(model);

      if (validator.errors && validator.errors.length) {
        return { details: validator.errors };
      }
    };
  }

  const schemaValidator = createValidator(schema);

  return new JSONSchemaBridge(schema, schemaValidator);
})()
```

[Example playground](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoApAZQHkA5YgYwAsoBbAQwEoQAacCAezBmVEYBXeFxiMAblGQAzRgBs4HISLGSAIlDmMAnsgCMABgMd0ASzEAjOVHQz5ikFoubk8CIKgcwWqlBpc5dCgIOwVPEGhGdFIAOzldJFkwjhhaBkZkEHx8ZlwAXgA-XGAAHRjcXCouGJh4XEYAK3F83BioAHdcVCb8YHq5OQBRCG4IGCRcNw82XEE4DVlBOXhxyfcoXABfZgBuMoqqmrrUuiYW0vKKydN4awmAcgwsWBh7tn2r-G0wKAeuCwaUCo8DeHwqkB4wXgplgEwuVyuVBu2jhk2-v1w91qEFMMQA5vctu9Lgjaox4Bi-l8fg9sbiCUSwVdsVAEKjqRisW56W8ERUSiAoDFBPQBRMANoC4huVnwAUzAWoSTCqDy3ACgBCXCWUHEjAg6AFAF1GSSrgAvUxgdno2nc_G8sDkikQGIPcUGAC0AE4jcAAKybQmbYkIkNM6AAR0Epmg6AlXOgCF590tYBTZIp9yNoa2exiH2kghiwNM1UqkQpADV5KZ0OSuBB8Cd0rl4YjqrVcHq5HWGxAWo1xAA6Kr0MCmazNtJMXZlCMIQSugj0LhBOS5QrFJkVHt9kRN1frucFs0VUzSAh7-sH4fBUZ4ABkj-7tZvjbvI0bMGH1nx8BoNsdyuaB4CXco-iCeBGEnVZr37T8HzzYDNiZTZ8wqVDTwOTtjhnRga17d8BzyCsoHJKBCP3Rtp1OFh8w-UDwNaDpcBIChqDojUcXQPEoFo9IZhbJgqOIk9thydgQBgfx2gASTiXEoGGUZQgcRgYG0EtYmIQQLHoG41PCDStKoWJRIooyQxAACGCkFA4CYGJoSoEBNiAA)

Screenshot Firefox 78

![Screenshot_20210211_140129](https://user-images.githubusercontent.com/2534896/107622865-ee4c1580-6c71-11eb-9fa1-0a49afa5de2e.png)

**Comment by radekmie** [comment]
Hi @slavb18. Thanks for the report! It looks like it's caused by the [`selection` class](https://github.com/vazco/uniforms/blob/ec5030886f0af285657583e58654b29ef280c153/packages/uniforms-semantic/src/SelectField.tsx#L80). Simply removing it removes the hover effect, therefore we'd need a different solution here. And thanks for the styles workaround - we'd rather try other approaches first.

**Comment by radekmie** [comment]
I did some experiments and here's what I've found:
1. Remove the `selection` class. Drawback: there's no focus and hover state.
2. Set `height: initial` (or `height: unset`). Drawback: the `select` is _slightly_ taller (38px -> 43px).
3. Set `padding: 0.5em` (replicating the `select.ui.dropdown` padding) or `padding-top: 0; padding-bottom: 0`. Drawback: magic values in the code.

All approaches render text not clipped, and every single one has some drawback. @slavb18, @Monteth, @wadamek65 - opinions?

**Comment by wadamek65** [comment]
@radekmie 

1. I think this is the worst option out of the three as it will also hurt accessibility.
2. This also requires magic values in the code just like step 3. with the additional drawback of making the styles inconsistent.
3. I think this is the way to go. This is mainly because we are somewhat "misusing" the semantic package. In semantic documentation examples the actual `select` component is only there for accessibility but is hidden from the viewport. The visible label and select components are a bunch of `div`s with the same classes that we are using. The fact we are applying them on a native `select` component is causing this issue so I think it is natural that we also have to adjust the styles by changing the padding.
