### ISSUE TITLE
Ts error: Unused '@ts-expect-error' directive.  TS2578

### ISSUE THREAD

**Issue by cesarve77** [vazco/uniforms#904]
I'm, using typescript 4.2.2
uniforms 3.2.1

/node_modules/uniforms-bootstrap4/src/gridClassName.ts
TypeScript error in /node_modules/uniforms-bootstrap4/src/gridClassName.ts(47,9):
Unused '@ts-expect-error' directive.  TS2578

    45 |       (Object.keys(grid) as GridSize[])
    46 |         .sort(compareSizeClass)
  > 47 |         // @ts-expect-error Weird type refinement problem.
       |         ^
    48 |         .map(size => gridClassNamePart(size, grid[size], side))
    49 |         .join(' ')
    50 |     );

**Comment by wadamek65** [comment]
Hey there, thanks for the report @cesarve77 

It seems like the issue was introduced here: https://github.com/vazco/uniforms/pull/887/files#diff-3376e8270059d06746fecc5dc4bf793f82f7bd219808eb943e9a1d503a44e971R47

Seems like new typescript version no longer has a problem with the types there (we are using 4.1.3 in uniforms). So a workaround for you for now: downgrade the version to 4.1.3 where it should hopefully work.

**Comment by wadamek65** [comment]
Update:

I tried updating TypeScript version to the newest one so that we can also get rid of this directive but I unfortunately encountered a problem which seems to be a bug in TypeScript 4.2+ [reported here.](https://github.com/microsoft/TypeScript/issues/42079)

[Reproduction of the broken declaration files that were generated after bumping up the version here.](https://www.typescriptlang.org/play?ts=4.2.3#code/JYWwDg9gTgLgBASQHZgK4wDRwN6JegBSgjAGc4BfOAM2JDgHIBDJGAEwHoAbYAIw+D4YDANwBYAFChIsOACUApkwDGmHPKWqAchDYKsi6pRp1GUTcPFTw0eLgBiwBVzZESpLMohIkC1Y+c2LGpgLhgFKAARAHkAWTcyLGiANwioYD1jWgh6BlQkYGpoEFJRSWlbOABFVAVSGGBvAGFgKGUuBWj0Hl82ExzGAAEWGABaPVJgAHMkAS8kUg4auobm1vbO7sEFNjLrGXh7YqwHYoRwkATyKmzckc4efiKoED2K2QAVCAgw4DB+u6sB58Dgwb6-MB7SQwACeYAUcAA6lAmGB4VArnAALxwFJpDIKAA8kjgcCOL3OCkuxESJJwdNJaWgAH4AFxwfIAayQEAA7kgrKTGVBiFBYnVSEwpgo2XB6ukkFNBULBEVZfLBEqGXKABZ85A9BQAURFLPZvHBSgF2t5KLREQAyrCOrKILwAFZ+GDKiiSAB8Vkk83qcD01CYqDCyNR6KdMI62PUICYUCmggAQhAYGCQOyGABGABMYAAHgxKIGJNR8qpGkg4LbUQEXAAKOnYbVeLjeDDaplQXsSIVwfvi0iS6WD4cKEswFFToU65xgBekjKruCqiAbrhMXjOHd75xNH4b8wAR1QrR2G9Iet5Bu2JtFG+STB4bCY4SdX9QHhtdroieXAbo29pQHGCY4mGEZRoBjrOvodIUOy0bgVcC7KDqoRsOYSDsooKgwDoeiDgAlPSQ5wMG8C7vuXAkQiOIAITMXRzhwAAZJxcBtlRpKEqQYAsH62qktg7FcL6-FCtgrFblxPF8cOw6CcJSCiTJKlcUgvBCcq2kCV8PwNP8DQwB0WLYFuFCaYZKmEss9R1i0bQdF0FnbH0HB2fZcCEhwxkQr52kBUJIliXAZHSapHDhRpdJkZWpLmDAqBQPWylCoS5IgAAdJSICRV23hWSVSAxSpOpMKQ9gKDsvAqJykVLlwYBWa1-wAD5dbxd76kghrPtAilwKx-ajaOEpSgo0WRTOc5MFZC0opVw46jAIBcOSVkZGtQqSVZkmMftpKScBR1HlwwGnXAF5XuYbBWfd15sLd9TxgoVlgbGiG3W+H5fgoP5paQy2mlAcDMow-bluyAMZEDIN-rdP0RBd2Bo1AN3aiFslYTheH7QFuUFRcvlJZI0mSHo7QpgiIC6JGCJ5AUzwlOWHZUYI4RQOGygIo4YQRDE8Q0uQXPDlhfichaJZ1OyvipFABnUT83iKwoyuq2wwCSrwHSFZr2vaudPzGxEqsI5+34wL+pAWyrAExuj5twErlvO+BkEKI7PpU5IkghMLURxFceXmGm9QRFlDDS8ossQPLpQLnH6tIAwqe6-rhsXJndIMGbXD51RDDW0jdugyXpIMFjwHV4wWM+yXlMSIHEgzgccCwvCcAfAtzauOLiaD1cxJURqioLtEIDADAhLIGgMAYYw3iKKQCjCH6C64IIS+GLKhgL0IfqUP6lbVkgtbeH3C0tmA4vsv3s6j+LFGS3dm-pfWYGD1lpIP3cBuY+S9IrZz3B0J62BAFkDyuAg2OxbpICYCAL60DxZ5WQag26zRqqKjQVrBQrBsSnxgaQPKuCWDShbIQ1geU7apk3nlAGtQ5paTgGAXcAs9QuAiFZMheVOEqAUDwvQUBbrmCYGwaIg0YT8IwZI6RsiJEKGoPI9weU97oEMLdHuaCBF6KhtDBg4RZwMH+u+Wo6jYEsIRMyYx5jIrYDyi44OvNRZXHvm-faPkFyt2ph3EsXcYKRngPMXw-gnCtmfmoXAnJBBsDzB0Jg1BywUFbkAA)

We'll have to decide if we want to create a temporary PR with a band-aid solution by changing this back to ignore-error or wait for the TS fix.

**Comment by radekmie** [comment]
@wadamek65: have you tried it recently?

**Comment by wadamek65** [comment]
@radekmie @cesarve77 

I came back to this today and the problem still seems to exists on TS version 4.2.4 and also on 4.3 beta. The issue I linked in my previous comment is still open. We will have to keep monitoring this as it is still blocking us from updating the TS version.
