### ISSUE TITLE
pathToName from JSONSchemaBridge does not handle properties with whitespaces

### ISSUE THREAD

**Issue by ljmotta** [vazco/uniforms#909]
Hi, this is my first issue here :grin: . I've came across of what I believe it is a bug on the JSONSchemaBridge. To be more precise, a bug on the `pathToName` method.

https://github.com/vazco/uniforms/blob/66e40d860b8f01ae024c257a6f60f6599d2615f0/packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts#L57-L66

As we can see on this piece of code on the last line, it performs a `slice(1)`. This slice makes this method return a wrong string if you have a property that contains whitespace on the top level of your schema.

A property with whitespace is represented as `"['My Property']"` and a common property is `".myProperty"`.

**Version**: any (since the creation of this file)

An example of a schema that doesn't work correctly:
```
{
  type: "object",
  properties: {
    "My Property": {
      required: ["someValue"],
      type: "object",
      properties: {
        someValue: {
          type: "number"
        }
      }
    }
  }
}
```

The `someValue` property will not be validated correctly because `pathToName` will return `"'My Property']"` instead of `"My Property"` (I'm not sure if this should be the correct return, but it is what my tests suggest).

**Comment by radekmie** [comment]
Hi @ljmotta, thanks for the report! It looks like you are using the old format of ajv errors. Since v7 the default one is `jsonPointers: true` (to enable the old style in v7 use `jsPropertySyntax: true`). Here's a [playground](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcICCATd0YwAQAoApAZQHkA5YgYwAsoBbAQwEoQAacCAezBmVEYBXeFxiMAblGQAzRgBs4HISLGSAIlDmMAnsgCMABgMd0ASzEAjOVHQz5ikFoubk8CIKgcwWqlBpc5dCgIOwVPEGhGdFIAOzldJFkwjhhaBkZkEHx8ZlwAXgA-XGAAHRjcXCouGJh4XEYAK3F83BioAHdcVCb8YHq5OQBRCG4IGCRcNw82XAaYAAVuMGD4bWJtGPhGAA8Jqc9cQTgNWUE5eHHJ9wOAayhtdq4IdEuAbRKQQRjTaSf6GA-AF1cABfZgAbjKFSqNTqqToTBapXKk20ywmHy4FgaUCo8A-bChuEgPBWplgE2RFQqHwAstpcItSRBVh9KUTqbhoABHQSmaDoCbvEAwLj0KAANXkHiBhJRnNW6NwmOxuPx7A51JJyxZ5MuVM51NF4qlcg87PlhoqiqgGJAMUE9GcEA-ms5ILdoM1HpRPpBkJiROkXzxpmqlUi8El8lM6EYIgg-Hh6VyBuh1VquHEMbjCZajXEADoqvQwKZrEm0kwIWVNdB4IIIOV8PQuEE5LlCsVPdm5LH408W23NDXA5aKj8CL3-wnC8FRngAGSLrM5gcQOcjJ4wQvWGIAc3gNFTnoq9cb5T6QS25cu09zT03C9BAatPvdr69Y_TsNwyaYpozk8LRUJG0Z9g-ib_iwAZEueTatB0uAkBQ1AIowABCECxvuUCVuhMzQYBkGjmCOTsCK_jtAAknEphtMMoyhA4jAwBsVCxMQggWPQpiIIk9jhKx7GxMR8ZSAJYQghwR4MBJICMJstggkAA) presenting this problem. Anyway, I agree we have to fix that.

**Comment by ljmotta** [comment]
@radekmie Thanks for addressing this issue so quickly! Yes I'm using an old format of ajv. My setup is ajv v6 (and ajv errors v1 due to compatibility) beucase my schema is draft4.
