### ISSUE TITLE
Issue: useForm must be used within a form

### ISSUE THREAD

**Issue by tnohtition** [vazco/uniforms#962]
I have an error message on the `production` build as `useForm must be used within a form`. Everything seems ok on the local machine.
The issue occurs many times but after I upgrade the `uniforms` to the newest version then the error was gone.
Please give me any helps. Thank you so much

**Comment by radekmie** [comment]
Hi @tnohtition. It's hard to tell what could cause this discrepancy between the development and the production builds. Have you tried building the production version and running it locally?

We'd need more information: what version were you using when the error happened, and what version solved it. Also, what build system are you using (Meteor, Webpack, Parcel, etc.)? And finally, it'd be great to have this error stack trace.

**Comment by tnohtition** [comment]
> Hi @tnohtition. It's hard to tell what could cause this discrepancy between the development and the production builds. Have you tried building the production version and running it locally?

This is a strange error for example I built a production build and deploy it on 01 May 2021 everything works completely. After some days (maybe other team members make other builds or not) the error occurs I do another build without any changes but the error still there so I have to upgrade to the new version and rebuild then the error was gone.
> 
> We'd need more information: what version were you using when the error happened, and what version solved it. Also, what build system are you using (Meteor, Webpack, Parcel, etc.)? And finally, it'd be great to have this error stack trace.
We use `nx` for the project and `Webpack` as the builder. Because the error only occurs on the `production` build so I don't think the stack trace is useful.

**Comment by radekmie** [comment]
Well, this means we won't be able to debug it easily. In general stack traces are useful, even when minified - we can at least check "how far" from React the error is.

I've put more thought into it, and I have a theory. It's often the case, that due to upgrades, some packages are in incompatible versions. This leads to multiple versions of the same package in `node_modules`. For example, if you'd update only the bridge or the theme, it'd install its own copy of uniforms in the newer version. Now, this leads to two `createContext` calls - one for the application, the other required by your dependency. To make sure it's not this problem, please do check the `package-lock.json` of your app **before** the update. If you see multiple `uniforms` occurrences, we've found the culprit. If not, let's wait until it happens again.

**Comment by radekmie** [comment]
As there's no follow-up here, I'm closing. Do let us know if you'll find anything that may help to prevent such problems.

**Comment by itaifish** [comment]
@radekmie You were right, I had the same error message and it was solved by removing the extra uniforms references in the yarn lock file.
